const fs = require('fs');

let content = fs.readFileSync('src/curriculum.js', 'utf8');

const blocks = {
    '1': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: Bilişimle Tanışıyorum (Teknolojik araçlar ve kullanım alanları)\", \"2. ÜNİTE: Bilgisayarın Parçaları (Fare, klavye, ekran ve kasa fonksiyonları)\", \"3. ÜNİTE: Doğru Oturuş ve Sağlık (Ergonomi ve ekran mesafesi kuralları)\", \"4. ÜNİTE: Dijital Vatandaşlığa Giriş (İnternette nezaket (Netiket))\", \"5. ÜNİTE: Algoritma Dünyası (Adım adım talimat verme (Bilgisayarsız))\", \"6. ÜNİTE: Yön Komutları (Karakterleri hedefe ulaştırma oyunları)\", \"7. ÜNİTE: Çizim Araçları (Dijital ortamda ilk görsel tasarımlar)\", \"8. ÜNİTE: Güvenli İnternet (Özel bilgileri koruma ve yardım isteme)\"],",
    '2': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: Teknoloji ve Ben (Günlük hayattaki dijital yardımcılarımız)\", \"2. ÜNİTE: Klavye ve Fare Kullanımı (Tuşların görevleri ve sürükle-bırak)\", \"3. ÜNİTE: Dosya ve Klasör (Bilgilerimizi nasıl saklarız?)\", \"4. ÜNİTE: Dijital Güvenlik (Güçlü şifre oluşturma yöntemleri)\", \"5. ÜNİTE: Döngüsel Algoritmalar (Tekrar eden işlerin mantığı)\", \"6. ÜNİTE: Bloklarla Kodlama (Basit bloklarla karakter yönetimi)\", \"7. ÜNİTE: İnternette Bilgi Arama (Görsel ve metin arama teknikleri)\", \"8. ÜNİTE: Medya Okuryazarlığı (Gördüğümüz her şey gerçek mi?)\"],",
    '3': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: Bilişim Etiği (Telif hakları ve dijital paylaşım kuralları)\", \"2. ÜNİTE: İşletim Sistemleri (Windows, Android ve iOS dünyası)\", \"3. ÜNİTE: Bulut Depolama (Google Drive ve OneDrive kullanımı)\", \"4. ÜNİTE: Kelime İşlemci - I (Metin yazma, kalınlaştırma ve renklendirme)\", \"5. ÜNİTE: Algoritmik Düşünme (Problem çözme ve akış şeması mantığı)\", \"6. ÜNİTE: Scratch ile Kodlama (İlk animasyonumu yapıyorum)\", \"7. ÜNİTE: Siber Zorbalık (Dijital zorbalıkla baş etme yöntemleri)\", \"8. ÜNİTE: Robotlar Nasıl Çalışır? (Sensörler ve motorların görevi)\"],",
    '4': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: Donanım ve Yazılım (Bilgisayarın iç birimleri (RAM, İşlemci, HDD))\", \"2. ÜNİTE: Arama Stratejileri (Doğru bilgiye hızlı ulaşma yöntemleri)\", \"3. ÜNİTE: Sunum Programları (Etkili slayt hazırlama teknikleri)\", \"4. ÜNİTE: Koşul Yapıları (\\\"Eğer\\\" ise mantığıyla karar verme)\", \"5. ÜNİTE: Hata Ayıklama (Kodlardaki yanlışları bulma (Debugging))\", \"6. ÜNİTE: Dijital Oyun Tasarımı (Kendi basit oyunumun kurallarını yazma)\", \"7. ÜNİTE: E-Okul ve E-Devlet (Dijital devlet hizmetlerini tanıma)\", \"8. ÜNİTE: Yapay Zeka Nedir? (Akıllı makineler nasıl öğrenir?)\"],",
    '5': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: Bilişim Etiği ve Sosyal Medya (Dijital ayak izi ve mahremiyet)\", \"2. ÜNİTE: Siber Güvenlik (Virüsler, truva atları ve korunma)\", \"3. ÜNİTE: Bilgisayar Sistemleri (Giriş, çıkış ve depolama birimleri)\", \"4. ÜNİTE: Bilgisayar Ağları (Modemin yapısı ve internetin yayılımı)\", \"5. ÜNİTE: Problem Çözme Süreci (Analiz, tasarım ve uygulama)\", \"6. ÜNİTE: Algoritmalar ve Akış Şemaları (Standart sembollerle algoritma çizimi)\", \"7. ÜNİTE: Blok Tabanlı Programlama (Değişkenler ve veri türleri)\", \"8. ÜNİTE: Müzik ve Ses Düzenleme (Dijital ses dosyalarıyla çalışma)\"],",
    '6': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: Bilişim Teknolojileri ve Değişim (Teknolojinin tarihsel gelişimi)\", \"2. ÜNİTE: Dijital Ortamda İş Birliği (Google Dokümanlar ile ortak çalışma)\", \"3. ÜNİTE: Hesaplama Çizelgeleri (Excel) (Satır, sütun ve hücre mantığı)\", \"4. ÜNİTE: Fonksiyonlar ve Formüller (Otomatik hesaplama araçları)\", \"5. ÜNİTE: Olay Yönetimi (Programlarda tetikleyici olaylar)\", \"6. ÜNİTE: Proje Geliştirme (Scratch ile kapsamlı bir uygulama süreci)\", \"7. ÜNİTE: Nesnelerin İnterneti (IoT) (Akıllı ev sistemleri)\", \"8. ÜNİTE: Bilişim Hukuku (İnternet suçları ve yaptırımlar)\"],",
    '7': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: 3B Tasarım ve Modelleme (Tinkercad ile üç boyutlu dünyalar)\", \"2. ÜNİTE: Grafik Tasarımı (Piksel ve vektör tabanlı görseller (Canva/GIMP))\", \"3. ÜNİTE: Web Tasarımına Giriş (HTML etiketleri ve yapı)\", \"4. ÜNİTE: Stil Sayfaları (CSS ile web sitesini renklendirme)\", \"5. ÜNİTE: Algoritma Analizi (En kısa yol ve verimlilik)\", \"6. ÜNİTE: Mobil Programlama (App Inventor ile mobil arayüz)\", \"7. ÜNİTE: Veri Madenciliği Giriş (Verilerin analiz edilmesi)\", \"8. ÜNİTE: Siber Tehdit Avcılığı (Phishing (Oltalama) ve korunma)\"],",
    '8': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: Metin Tabanlı Programlama (Python programlama diline geçiş)\", \"2. ÜNİTE: Değişkenler ve Giriş-Çıkış (Python'da input ve print)\", \"3. ÜNİTE: Kontrol Yapıları (If-Elif-Else yapıları)\", \"4. ÜNİTE: Döngüler (For ve While döngüleri)\", \"5. ÜNİTE: Robotik Kodlama (Arduino kartı ve bileşenleri)\", \"6. ÜNİTE: Sensör Uygulamaları (Mesafe ve ışık sensörü kullanımı)\", \"7. ÜNİTE: Yapay Zeka ve Gelecek (ChatGPT ve benzeri sistemlerin mantığı)\", \"8. ÜNİTE: Bilişim Meslekleri (Geleceğin iş dünyasına hazırlık)\"],",
    '9': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: Bilgi İşlemisel Düşünme (Karmaşık sorunların modellenmesi)\", \"2. ÜNİTE: Gelişmiş Algoritmalar (Sözde kod (Pseudocode) yazımı)\", \"3. ÜNİTE: Python ile Programlama - I (Temel söz dizimi ve operatörler)\", \"4. ÜNİTE: Listeler ve Koleksiyonlar (Diziler ve veri saklama yöntemleri)\", \"5. ÜNİTE: Dijital Okuryazarlık (Dijital içerik üretimi ve yönetimi)\", \"6. ÜNİTE: Ağ Protokolleri (HTTP, FTP, IP kavramları)\", \"7. ÜNİTE: Veri Güvenliği ve Gizlilik (Şifreleme (Kriptoloji) temelleri)\", \"8. ÜNİTE: Bilişim ve Girişimcilik (Startup kültürü ve dijital pazarlama)\"],",
    '10': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: Python ile Programlama - II (Fonksiyonlar ve parametreler)\", \"2. ÜNİTE: Modüler Programlama (Kütüphane kullanımı ve oluşturma)\", \"3. ÜNİTE: Veritabanı Sistemleri (SQL sorguları ve tablo yapıları)\", \"4. ÜNİTE: Arayüz Tasarımı (Tkinter veya PyQt ile pencereli uygulamalar)\", \"5. ÜNİTE: Yazılım Yaşam Döngüsü (Tasarım modelleri ve test süreçleri)\", \"6. ÜNİTE: Mobil Uygulama Geliştirme (Flutter veya React Native temelleri)\", \"7. ÜNİTE: Veri Görselleştirme (Matplotlib ile grafik çizimi)\", \"8. ÜNİTE: Blockchain ve Kripto (Dağıtık defter teknolojisi)\"],",
    '11': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: Nesne Yönelimli Programlama (OOP) (Class, Object, Inheritance)\", \"2. ÜNİTE: Web Frameworks (Django veya Flask ile arka yüz (Backend))\", \"3. ÜNİTE: Sunucu Teknolojileri (Linux komut satırı ve sunucu kurulumu)\", \"4. ÜNİTE: Siber Güvenlik - İleri (Sızma testleri ve savunma stratejileri)\", \"5. ÜNİTE: Yapay Zeka ve Makine Öğrenmesi (Scikit-learn ile modelleme)\", \"6. ÜNİTE: Görüntü İşleme (OpenCV ile görsel analiz)\", \"7. ÜNİTE: Büyük Veri Analizi (Pandas kütüphanesi ile veri işleme)\", \"8. ÜNİTE: Bilişim Proje Yönetimi (Agile ve Scrum çalışma prensipleri)\"],",
    '12': "\\n    'Bilişim Teknolojileri ve Yazılım': [\"1. ÜNİTE: Yapay Sinir Ağları (Derin öğrenme ve Keras/TensorFlow)\", \"2. ÜNİTE: Doğal Dil İşleme (NLP) (Metinlerin bilgisayarca anlamlandırılması)\", \"3. ÜNİTE: Sanal ve Artırılmış Gerçeklik (Unity ile 3D uygulama geliştirme)\", \"4. ÜNİTE: Gömülü Sistemler (Raspberry Pi ile Linux tabanlı projeler)\", \"5. ÜNİTE: Akıllı Şehirler ve IoT (Şehir yönetimi ve sensör ağları)\", \"6. ÜNİTE: Finansal Teknolojiler (Dijital bankacılık ve güvenli ödeme)\", \"7. ÜNİTE: Bilişim ve Etik Sorunlar (Transhümanizm ve AI etiği)\", \"8. ÜNİTE: Bitirme Projesi (Yıl sonu dijital ürün tasarımı ve sunumu)\"],"
};

for (let i = 1; i <= 11; i++) {
    const searchString = '  },\\r\\n  ' + (i + 1) + ': {';
    let newContent = content.replace(searchString, blocks[i] + '  },\\r\\n  ' + (i + 1) + ': {');
    if (newContent === content) {
        const searchStringLF = '  },\\n  ' + (i + 1) + ': {';
        newContent = content.replace(searchStringLF, blocks[i] + '  },\\n  ' + (i + 1) + ': {');
    }
    content = newContent;
}

const search12 = '  },\\r\\n};';
let newContent = content.replace(search12, blocks['12'] + '\\r\\n  },\\r\\n};');
if (newContent === content) {
    const search12LF = '  },\\n};';
    newContent = content.replace(search12LF, blocks['12'] + '\\n  },\\n};');
}
content = newContent;

fs.writeFileSync('src/curriculum.js', content);
