const fs = require('fs');

let content = fs.readFileSync('src/curriculum.js', 'utf8');
let lines = content.split(/\r?\n/);

const blocks = {
    '1': `    'Görsel Sanatlar': ["1. ÜNİTE: Sanata Merhaba (Görsel sanatlar araç gereçlerini tanıma ve doğru kullanım)", "2. ÜNİTE: Nokta ve Çizgi (Çizgi çeşitleri ile temel yüzey çalışmaları)", "3. ÜNİTE: Ana Renkler (Kırmızı, sarı ve mavinin dünyası)", "4. ÜNİTE: Doğadaki Şekiller (Geometrik ve organik formları fark etme)", "5. ÜNİTE: Kes-Yapıştır (Kolaj) (Kağıt işleri ve basit kolaj uygulamaları)", "6. ÜNİTE: Kil ve Hamur (Üç boyutlu parmak çalışmaları)", "7. ÜNİTE: Müze Bilinci (Sanat eserlerine nasıl bakılır?)", "8. ÜNİTE: Özel Gün Kartları (Tebrik kartı tasarımı ve süsleme)"],`,
    '2': `    'Görsel Sanatlar': ["1. ÜNİTE: Renklerin Karışımı (Ara renkleri oluşturma (Turuncu, Yeşil, Mor))", "2. ÜNİTE: Doku Çalışmaları (Çizgisel ve gerçek doku örnekleri)", "3. ÜNİTE: Mekan ve Yerleşim (Kağıt üzerinde alt-üst, ön-arka kavramları)", "4. ÜNİTE: Portreye Giriş (Kendi yüzümüzü tanıyalım (Otoportre))", "5. ÜNİTE: Atıklarla Sanat (Geri dönüşüm malzemelerinden tasarım)", "6. ÜNİTE: Milli Bayramlarımız (Kutlama görselleri ve afiş hazırlama)", "7. ÜNİTE: Geleneksel Motifler (Basit Türk motifleri ve desenler)", "8. ÜNİTE: İz Bırakan Sanatçılar (Ünlü tabloları tanıma ve yorumlama)"],`,
    '3': `    'Görsel Sanatlar': ["1. ÜNİTE: Işık ve Gölge (Cisimlerin hacim kazanması)", "2. ÜNİTE: Sıcak ve Soğuk Renkler (Renklerin psikolojik etkileri)", "3. ÜNİTE: Baskı Sanatı - I (Patates, yaprak veya sünger baskısı)", "4. ÜNİTE: Figür Çizimi (İnsan vücudunun temel oranları)", "5. ÜNİTE: Kültürel Miras (Tarihi mekanları tanıma ve resmetme)", "6. ÜNİTE: Tasarım ve Fonksiyon (Günlük eşyaların estetiği)", "7. ÜNİTE: Maske Tasarımı (Kağıt tabaklardan üç boyutlu maskeler)", "8. ÜNİTE: Sanat Eleştirisi (Bir sanat eserini beğenme kriterleri)"],`,
    '4': `    'Görsel Sanatlar': ["1. ÜNİTE: Perspektife Giriş (Uzaklık ve yakınlık algısı)", "2. ÜNİTE: Tamamlayıcı Renkler (Kontrast renklerin kullanımı)", "3. ÜNİTE: Karikatür Dünyası (Abartı ve mizahın sanattaki yeri)", "4. ÜNİTE: Ebru Sanatı (Su üzerindeki renklerin dansı (Geleneksel sanatlar))", "5. ÜNİTE: Mimari Tasarım (Hayalimdeki ev veya okul modeli)", "6. ÜNİTE: Grafik Sanatlar (Yazı ve resim birlikteliği (Tipografi girişi))", "7. ÜNİTE: Kukla Yapımı (Hareketli figür tasarımları)", "8. ÜNİTE: Sanat Galerisi (Sınıf sergisi planlama ve sunum)"],`,
    '5': `    'Görsel Sanatlar': ["1. ÜNİTE: Görsel Algı (Optik illüzyonlar ve göz yanılsamaları)", "2. ÜNİTE: Leke ve Ton (Kurşun kalemle derecelendirme çalışmaları)", "3. ÜNİTE: Renk Armonileri (Monokromatik (tek renk) tasarımlar)", "4. ÜNİTE: Seramik Sanatı (Çimdik ve fitil tekniği ile form oluşturma)", "5. ÜNİTE: Doğa ve Peyzaj (Manzara resminde derinlik)", "6. ÜNİTE: Dijital Sanat - I (Tablet ve bilgisayarda çizim araçları)", "7. ÜNİTE: Kültürel Motifler (Çini ve hat sanatına giriş)", "8. ÜNİTE: Afiş Tasarımı (Belirli bir konu üzerine görsel mesaj oluşturma)"],`,
    '6': `    'Görsel Sanatlar': ["1. ÜNİTE: Anatomi ve Oran-Orantı (Hareketli figür çizimleri)", "2. ÜNİTE: Açık-Koyu Etkisi (Desen çalışmalarında hacimleme)", "3. ÜNİTE: Baskı Teknikleri - II (Linol veya şablon (stok) baskı)", "4. ÜNİTE: Perspektif Kuralları (Tek kaçışlı perspektif çizimi)", "5. ÜNİTE: Modern Sanat Akımları (Kübizm ve Empresyonizm (İzlenimcilik))", "6. ÜNİTE: Logo ve Amblem (Kurumsal kimlik tasarım mantığı)", "7. ÜNİTE: Heykel ve Mekan (Kamusal alandaki heykelleri tanıma)", "8. ÜNİTE: Fotoğraf Sanatı (Kompozisyon kuralları ve ışık)"],`,
    '7': `    'Görsel Sanatlar': ["1. ÜNİTE: Renk Teorisi ve Psikolojisi (Renk çemberi ve zıtlıklar)", "2. ÜNİTE: İki Kaçışlı Perspektif (Köşe görünümlü yapı çizimleri)", "3. ÜNİTE: Tekstil Sanatı (Kumaş boyama veya dokuma denemeleri)", "4. ÜNİTE: Minyatür Sanatı (Geleneksel minyatür teknikleri ve hikayeleştirme)", "5. ÜNİTE: Dışavurumculuk (Ekspresyonizm) (Duyguların renklerle anlatımı)", "6. ÜNİTE: Pop-Art (Popüler kültürün sanatla buluşması)", "7. ÜNİTE: Stop-Motion (Görsellerle basit animasyon oluşturma)", "8. ÜNİTE: Estetik ve Etik (Sanatta özgünlük ve intihal)"],`,
    '8': `    'Görsel Sanatlar': ["1. ÜNİTE: Gölgeleme ve Desen (Kömür kalem (füzen) teknikleri)", "2. ÜNİTE: İmgesel Tasarım (Hayalden kompozisyon kurma)", "3. ÜNİTE: Endüstriyel Tasarım (Ürün geliştirme ve estetik)", "4. ÜNİTE: Sanat Tarihi Kronolojisi (Rönesans’tan günümüze yolculuk)", "5. ÜNİTE: Soyut Sanat (Form ve rengin serbest kullanımı)", "6. ÜNİTE: Enstalasyon (Yerleştirme) (Mekana özgü sanat çalışmaları)", "7. ÜNİTE: Portre ve Karakter (Farklı duyguların yüz ifadelerine yansıması)", "8. ÜNİTE: Geleceğin Sanatı (Yapay zeka ve dijital enstalasyonlar)"],`,
    '9': `    'Görsel Sanatlar': ["1. ÜNİTE: Görsel Okuryazarlık (İmajları okuma ve anlamlandırma)", "2. ÜNİTE: Çizgi ve Form (Temel sanat eğitimi ilkeleri)", "3. ÜNİTE: Renk Bilgisi ve Uygulama (Guaj ve sulu boya teknikleri)", "4. ÜNİTE: Perspektif ve Hacim (Nesne etütleri ve mekan çizimi)", "5. ÜNİTE: Antik Sanat (Mezopotamya, Mısır ve Anadolu uygarlıkları)", "6. ÜNİTE: Sanat ve Toplum (Sanatın toplumsal değişimdeki rolü)", "7. ÜNİTE: Dijital İllüstrasyon (Grafik tablet uygulamaları)", "8. ÜNİTE: Sanat Eleştirisi Yöntemleri (Betimleme, analiz, yorum ve yargı)"],`,
    '10': `    'Görsel Sanatlar': ["1. ÜNİTE: Yağlı Boya/Akrilik Teknikleri (Katmanlı boyama yöntemleri)", "2. ÜNİTE: Figüratif Kompozisyon (Grup figür yerleşimleri)", "3. ÜNİTE: Batı Sanatı Tarihi (Barok, Rokoko ve Klasisizm)", "4. ÜNİTE: Grafik Tasarım ve Reklam (Görsel iletişim tasarımı)", "5. ÜNİTE: Geleneksel Türk Sanatları (Tezhip, Kat’ı ve Ebru derinleşme)", "6. ÜNİTE: İç Mekan Tasarımı (Dekorasyon ve estetik planlama)", "7. ÜNİTE: Sanat ve Teknoloji (Video-art ve dijital kolaj)", "8. ÜNİTE: Müze ve Galeri Yönetimi (Küratörlük kavramına giriş)"],`,
    '11': `    'Görsel Sanatlar': ["1. ÜNİTE: İleri Desen Çalışmaları (Canlı modelden çizimler)", "2. ÜNİTE: Modernizmden Postmodernizme (Sanat kuramları)", "3. ÜNİTE: Moda ve Kostüm Tasarımı (Tekstil ve estetik birlikteliği)", "4. ÜNİTE: Sinematografi (Sinemanın görsel dili ve estetiği)", "5. ÜNİTE: Çağdaş Türk Sanatı (Cumhuriyet dönemi sanatçıları)", "6. ÜNİTE: Sanat Felsefesi (Estetik) (Güzellik kavramı ve sanat tanımları)", "7. ÜNİTE: Çevresel Sanat (Land Art) (Doğayı sanat malzemesi olarak kullanma)", "8. ÜNİTE: Portfolyo Hazırlama (Sanatsal çalışmaları biriktirme ve sunma)"],`,
    '12': `    'Görsel Sanatlar': ["1. ÜNİTE: Kişisel Üslup Geliştirme (Kendi sanatsal dilini bulma)", "2. ÜNİTE: Disiplinlerarası Sanat (Müzik, edebiyat ve resim etkileşimi)", "3. ÜNİTE: Güncel Sanat Etkinlikleri (Bienaller ve sanat fuarları)", "4. ÜNİTE: Kreatif Endüstriler (Sanatla ilgili kariyer basamakları)", "5. ÜNİTE: Kamusal Sanat (Şehir mimarisi ve estetik dokunuşlar)", "6. ÜNİTE: Sanat ve Psikoloji (Sanat terapisine giriş)", "7. ÜNİTE: Yapay Zeka Sanatı ve Telif (Algoritmik sanatın hukuki boyutu)", "8. ÜNİTE: Mezuniyet Projesi (Bağımsız bir sanat eseri üretimi ve sergilenmesi)"],`
};

let grade = 1;
for (let i = 0; i < lines.length; i++) {
    if (lines[i] === '  },') {
        if (grade <= 12) {
            lines.splice(i, 0, blocks[grade.toString()]);
            grade++;
            i++; 
        }
    } else if (lines[i] === '};' && grade === 12) {
        
    }
}

fs.writeFileSync('src/curriculum.js', lines.join('\\n'));
console.log('Done appending Görsel Sanatlar. Grade is now:', grade);
