const fs = require('fs');
let content = fs.readFileSync('src/curriculum.js', 'utf8');

const additions = {
    '1': [
        `    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Okuluma Merhaba (Okul bahçesi ve güvenli oyun alanları)", "2. ÜNİTE: Vücudumu Tanıyorum (Temel anatomik bölgeler ve hareket kabiliyeti)", "3. ÜNİTE: Temel Hareketler - I (Yer değiştirme (koşma, galop, sıçrama))", "4. ÜNİTE: Temel Hareketler - II (Dengeleme (eğilme, esneme, dönme))", "5. ÜNİTE: Nesne Kontrolü - I (Top yuvarlama, durdurma ve atma)", "6. ÜNİTE: Oyun Dünyası (Basit kurallı sınıf ve bahçe oyunları)", "7. ÜNİTE: Kişisel Bakım (Spor sonrası temizlik ve düzen)", "8. ÜNİTE: Sağlıklı Beslenme (Sporcu öğünü ve su tüketimi)"],`,
        `    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Okuluma Merhaba (Okul bahçesi ve güvenli oyun alanları)", "2. ÜNİTE: Vücudumu Tanıyorum (Temel anatomik bölgeler ve hareket kabiliyeti)", "3. ÜNİTE: Temel Hareketler - I (Yer değiştirme (koşma, galop, sıçrama))", "4. ÜNİTE: Temel Hareketler - II (Dengeleme (eğilme, esneme, dönme))", "5. ÜNİTE: Nesne Kontrolü - I (Top yuvarlama, durdurma ve atma)", "6. ÜNİTE: Oyun Dünyası (Basit kurallı sınıf ve bahçe oyunları)", "7. ÜNİTE: Kişisel Bakım (Spor sonrası temizlik ve düzen)", "8. ÜNİTE: Sağlıklı Beslenme (Sporcu öğünü ve su tüketimi)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Bilişimle Tanışıyorum (Teknolojik araçlar ve kullanım alanları)", "2. ÜNİTE: Bilgisayarın Parçaları (Fare, klavye, ekran ve kasa fonksiyonları)", "3. ÜNİTE: Doğru Oturuş ve Sağlık (Ergonomi ve ekran mesafesi kuralları)", "4. ÜNİTE: Dijital Vatandaşlığa Giriş (İnternette nezaket (Netiket))", "5. ÜNİTE: Algoritma Dünyası (Adım adım talimat verme (Bilgisayarsız))", "6. ÜNİTE: Yön Komutları (Karakterleri hedefe ulaştırma oyunları)", "7. ÜNİTE: Çizim Araçları (Dijital ortamda ilk görsel tasarımlar)", "8. ÜNİTE: Güvenli İnternet (Özel bilgileri koruma ve yardım isteme)"],`
    ],
    '2': [
        `    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Hareketli Yaşam (Düzenli egzersizin vücuda etkileri)", "2. ÜNİTE: Kombine Hareketler (Koşarken nesne taşıma ve yön değiştirme)", "3. ÜNİTE: Eşli Oyunlar (Arkadaşıyla yardımlaşarak hareket etme)", "4. ÜNİTE: Nesne Kontrolü - II (Ayakla top sürme ve hedef vurma)", "5. ÜNİTE: Ritim ve Müzik (El çırpma ve tempo eşliğinde yürüyüş)", "6. ÜNİTE: Dikkat ve Koordinasyon (Tepki hızı gerektiren eğitsel oyunlar)", "7. ÜNİTE: Doğa Bilinci (Açık hava etkinlikleri ve çevre temizliği)", "8. ÜNİTE: Güvenli Hareket (Spor ekipmanlarını doğru kullanma)"],`,
        `    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Hareketli Yaşam (Düzenli egzersizin vücuda etkileri)", "2. ÜNİTE: Kombine Hareketler (Koşarken nesne taşıma ve yön değiştirme)", "3. ÜNİTE: Eşli Oyunlar (Arkadaşıyla yardımlaşarak hareket etme)", "4. ÜNİTE: Nesne Kontrolü - II (Ayakla top sürme ve hedef vurma)", "5. ÜNİTE: Ritim ve Müzik (El çırpma ve tempo eşliğinde yürüyüş)", "6. ÜNİTE: Dikkat ve Koordinasyon (Tepki hızı gerektiren eğitsel oyunlar)", "7. ÜNİTE: Doğa Bilinci (Açık hava etkinlikleri ve çevre temizliği)", "8. ÜNİTE: Güvenli Hareket (Spor ekipmanlarını doğru kullanma)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Teknoloji ve Ben (Günlük hayattaki dijital yardımcılarımız)", "2. ÜNİTE: Klavye ve Fare Kullanımı (Tuşların görevleri ve sürükle-bırak)", "3. ÜNİTE: Dosya ve Klasör (Bilgilerimizi nasıl saklarız?)", "4. ÜNİTE: Dijital Güvenlik (Güçlü şifre oluşturma yöntemleri)", "5. ÜNİTE: Döngüsel Algoritmalar (Tekrar eden işlerin mantığı)", "6. ÜNİTE: Bloklarla Kodlama (Basit bloklarla karakter yönetimi)", "7. ÜNİTE: İnternette Bilgi Arama (Görsel ve metin arama teknikleri)", "8. ÜNİTE: Medya Okuryazarlığı (Gördüğümüz her şey gerçek mi?)"],`
    ],
    '3': [
        `    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Hareket Kavramları (Hareketin hızı, yönü ve alanı (uzamsal farkındalık))", "2. ÜNİTE: Geleneksel Oyunlar - I (Unutulmaya yüz tutmuş sokak oyunları)", "3. ÜNİTE: Çabukluk ve Çeviklik (İstasyon çalışmaları ve engelli parkurlar)", "4. ÜNİTE: Takım Ruhu (Grup içi iletişim ve yardımlaşma oyunları)", "5. ÜNİTE: Esneklik ve Denge (Statik ve dinamik denge çalışmaları)", "6. ÜNİTE: Ritmik Adımlar (Basit halk oyunları adımları)", "7. ÜNİTE: Vücut Yönetimi (Kendi ağırlığıyla yapılan temel egzersizler)", "8. ÜNİTE: Fair-Play Giriş (Kazanma ve kaybetmeyi kabullenme)"],`,
        `    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Hareket Kavramları (Hareketin hızı, yönü ve alanı (uzamsal farkındalık))", "2. ÜNİTE: Geleneksel Oyunlar - I (Unutulmaya yüz tutmuş sokak oyunları)", "3. ÜNİTE: Çabukluk ve Çeviklik (İstasyon çalışmaları ve engelli parkurlar)", "4. ÜNİTE: Takım Ruhu (Grup içi iletişim ve yardımlaşma oyunları)", "5. ÜNİTE: Esneklik ve Denge (Statik ve dinamik denge çalışmaları)", "6. ÜNİTE: Ritmik Adımlar (Basit halk oyunları adımları)", "7. ÜNİTE: Vücut Yönetimi (Kendi ağırlığıyla yapılan temel egzersizler)", "8. ÜNİTE: Fair-Play Giriş (Kazanma ve kaybetmeyi kabullenme)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Bilişim Etiği (Telif hakları ve dijital paylaşım kuralları)", "2. ÜNİTE: İşletim Sistemleri (Windows, Android ve iOS dünyası)", "3. ÜNİTE: Bulut Depolama (Google Drive ve OneDrive kullanımı)", "4. ÜNİTE: Kelime İşlemci - I (Metin yazma, kalınlaştırma ve renklendirme)", "5. ÜNİTE: Algoritmik Düşünme (Problem çözme ve akış şeması mantığı)", "6. ÜNİTE: Scratch ile Kodlama (İlk animasyonumu yapıyorum)", "7. ÜNİTE: Siber Zorbalık (Dijital zorbalıkla baş etme yöntemleri)", "8. ÜNİTE: Robotlar Nasıl Çalışır? (Sensörler ve motorların görevi)"],`
    ],
    '4': [
        `    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Branş Hazırlık - I (Basketbol ve voleybol temel mekanikleri)", "2. ÜNİTE: Branş Hazırlık - II (Futbol ve hentbol temel mekanikleri)", "3. ÜNİTE: Strateji ve Taktik (Oyun içinde yer tutma ve paslaşma)", "4. ÜNİTE: Geleneksel Oyunlar - II (Yöresel oyunlar ve kuralları)", "5. ÜNİTE: Fiziksel Uygunluk (Boy, kilo ve nabız ölçüm takibi)", "6. ÜNİTE: İlkyardım Bilgisi (Küçük yaralanmalarda yapılacaklar)", "7. ÜNİTE: Milli Bayramlar (Tören düzeni ve bayram kutlamaları)", "8. ÜNİTE: Spor Etiği (Kurallara bağlılık ve rakibe saygı)"],`,
        `    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Branş Hazırlık - I (Basketbol ve voleybol temel mekanikleri)", "2. ÜNİTE: Branş Hazırlık - II (Futbol ve hentbol temel mekanikleri)", "3. ÜNİTE: Strateji ve Taktik (Oyun içinde yer tutma ve paslaşma)", "4. ÜNİTE: Geleneksel Oyunlar - II (Yöresel oyunlar ve kuralları)", "5. ÜNİTE: Fiziksel Uygunluk (Boy, kilo ve nabız ölçüm takibi)", "6. ÜNİTE: İlkyardım Bilgisi (Küçük yaralanmalarda yapılacaklar)", "7. ÜNİTE: Milli Bayramlar (Tören düzeni ve bayram kutlamaları)", "8. ÜNİTE: Spor Etiği (Kurallara bağlılık ve rakibe saygı)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Donanım ve Yazılım (Bilgisayarın iç birimleri (RAM, İşlemci, HDD))", "2. ÜNİTE: Arama Stratejileri (Doğru bilgiye hızlı ulaşma yöntemleri)", "3. ÜNİTE: Sunum Programları (Etkili slayt hazırlama teknikleri)", "4. ÜNİTE: Koşul Yapıları (\\"Eğer\\" ise mantığıyla karar verme)", "5. ÜNİTE: Hata Ayıklama (Kodlardaki yanlışları bulma (Debugging))", "6. ÜNİTE: Dijital Oyun Tasarımı (Kendi basit oyunumun kurallarını yazma)", "7. ÜNİTE: E-Okul ve E-Devlet (Dijital devlet hizmetlerini tanıma)", "8. ÜNİTE: Yapay Zeka Nedir? (Akıllı makineler nasıl öğrenir?)"],`
    ],
    '5': [
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Hareket Eğitimi (Temel duruşlar ve dizilişler)", "2. ÜNİTE: Atletizm (Koşu teknikleri ve bayrak yarışı)", "3. ÜNİTE: Voleybol (Parmak pas ve manşet pas temelleri)", "4. ÜNİTE: Basketbol (Top sürme ve şut mekaniği)", "5. ÜNİTE: Jimnastik (Öne ve arkaya takla, denge çalışmaları)", "6. ÜNİTE: Fiziksel Etkinlik (Haftalık egzersiz planı oluşturma)", "7. ÜNİTE: Spor Kültürü (Olimpiyat halkalarının anlamı ve tarihi)", "8. ÜNİTE: Beslenme Okuryazarlığı (Kalori hesabı ve paketli gıdalar)"],`,
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Hareket Eğitimi (Temel duruşlar ve dizilişler)", "2. ÜNİTE: Atletizm (Koşu teknikleri ve bayrak yarışı)", "3. ÜNİTE: Voleybol (Parmak pas ve manşet pas temelleri)", "4. ÜNİTE: Basketbol (Top sürme ve şut mekaniği)", "5. ÜNİTE: Jimnastik (Öne ve arkaya takla, denge çalışmaları)", "6. ÜNİTE: Fiziksel Etkinlik (Haftalık egzersiz planı oluşturma)", "7. ÜNİTE: Spor Kültürü (Olimpiyat halkalarının anlamı ve tarihi)", "8. ÜNİTE: Beslenme Okuryazarlığı (Kalori hesabı ve paketli gıdalar)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Bilişim Etiği ve Sosyal Medya (Dijital ayak izi ve mahremiyet)", "2. ÜNİTE: Siber Güvenlik (Virüsler, truva atları ve korunma)", "3. ÜNİTE: Bilgisayar Sistemleri (Giriş, çıkış ve depolama birimleri)", "4. ÜNİTE: Bilgisayar Ağları (Modemin yapısı ve internetin yayılımı)", "5. ÜNİTE: Problem Çözme Süreci (Analiz, tasarım ve uygulama)", "6. ÜNİTE: Algoritmalar ve Akış Şemaları (Standart sembollerle algoritma çizimi)", "7. ÜNİTE: Blok Tabanlı Programlama (Değişkenler ve veri türleri)", "8. ÜNİTE: Müzik ve Ses Düzenleme (Dijital ses dosyalarıyla çalışma)"],`
    ],
    '6': [
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Hentbol (Temel atışlar ve kale savunması)", "2. ÜNİTE: Masa Tenisi (Raket tutuşu ve servis çeşitleri)", "3. ÜNİTE: Badminton (Vuruş teknikleri ve saha çizgileri)", "4. ÜNİTE: Dayanıklılık (Orta mesafe koşuları ve nefes kontrolü)", "5. ÜNİTE: Halk Oyunları (Bölgesel oyunlar ve ritim çalışması)", "6. ÜNİTE: Öz Disiplin (Antrenman disiplini ve devamlılık)", "7. ÜNİTE: Engelliler ve Spor (Paralimpik branşları tanıma)", "8. ÜNİTE: Teknoloji ve Spor (Adım sayar ve mobil sağlık uygulamaları)"],`,
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Hentbol (Temel atışlar ve kale savunması)", "2. ÜNİTE: Masa Tenisi (Raket tutuşu ve servis çeşitleri)", "3. ÜNİTE: Badminton (Vuruş teknikleri ve saha çizgileri)", "4. ÜNİTE: Dayanıklılık (Orta mesafe koşuları ve nefes kontrolü)", "5. ÜNİTE: Halk Oyunları (Bölgesel oyunlar ve ritim çalışması)", "6. ÜNİTE: Öz Disiplin (Antrenman disiplini ve devamlılık)", "7. ÜNİTE: Engelliler ve Spor (Paralimpik branşları tanıma)", "8. ÜNİTE: Teknoloji ve Spor (Adım sayar ve mobil sağlık uygulamaları)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Bilişim Teknolojileri ve Değişim (Teknolojinin tarihsel gelişimi)", "2. ÜNİTE: Dijital Ortamda İş Birliği (Google Dokümanlar ile ortak çalışma)", "3. ÜNİTE: Hesaplama Çizelgeleri (Excel) (Satır, sütun ve hücre mantığı)", "4. ÜNİTE: Fonksiyonlar ve Formüller (Otomatik hesaplama araçları)", "5. ÜNİTE: Olay Yönetimi (Programlarda tetikleyici olaylar)", "6. ÜNİTE: Proje Geliştirme (Scratch ile kapsamlı bir uygulama süreci)", "7. ÜNİTE: Nesnelerin İnterneti (IoT) (Akıllı ev sistemleri)", "8. ÜNİTE: Bilişim Hukuku (İnternet suçları ve yaptırımlar)"],`
    ],
    '7': [
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: İleri Voleybol (Servis atma ve oyun kuralları)", "2. ÜNİTE: İleri Basketbol (Turnike ve savunma çeşitleri)", "3. ÜNİTE: Oryantiring (Harita okuma ve doğada yön bulma)", "4. ÜNİTE: Kuvvet ve Esneklik (Direnç bantları ile çalışma)", "5. ÜNİTE: Doping ve Zararları (Temiz spor bilinci)", "6. ÜNİTE: Spor Tarihi (Türk sporunun efsane isimleri)", "7. ÜNİTE: Zihin ve Spor (Odaklanma ve stres yönetimi)", "8. ÜNİTE: Sosyal Sorumluluk (Sporla toplumsal farkındalık projeleri)"],`,
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: İleri Voleybol (Servis atma ve oyun kuralları)", "2. ÜNİTE: İleri Basketbol (Turnike ve savunma çeşitleri)", "3. ÜNİTE: Oryantiring (Harita okuma ve doğada yön bulma)", "4. ÜNİTE: Kuvvet ve Esneklik (Direnç bantları ile çalışma)", "5. ÜNİTE: Doping ve Zararları (Temiz spor bilinci)", "6. ÜNİTE: Spor Tarihi (Türk sporunun efsane isimleri)", "7. ÜNİTE: Zihin ve Spor (Odaklanma ve stres yönetimi)", "8. ÜNİTE: Sosyal Sorumluluk (Sporla toplumsal farkındalık projeleri)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: 3B Tasarım ve Modelleme (Tinkercad ile üç boyutlu dünyalar)", "2. ÜNİTE: Grafik Tasarımı (Piksel ve vektör tabanlı görseller (Canva/GIMP))", "3. ÜNİTE: Web Tasarımına Giriş (HTML etiketleri ve yapı)", "4. ÜNİTE: Stil Sayfaları (CSS ile web sitesini renklendirme)", "5. ÜNİTE: Algoritma Analizi (En kısa yol ve verimlilik)", "6. ÜNİTE: Mobil Programlama (App Inventor ile mobil arayüz)", "7. ÜNİTE: Veri Madenciliği Giriş (Verilerin analiz edilmesi)", "8. ÜNİTE: Siber Tehdit Avcılığı (Phishing (Oltalama) ve korunma)"],`
    ],
    '8': [
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Müsabaka Yönetimi (Hakemlik işaretleri ve oyun yönetimi)", "2. ÜNİTE: Taktik Geliştirme (Karmaşık oyun stratejileri)", "3. ÜNİTE: Bireysel Gelişim (Kişisel fiziksel uygunluk karnesi)", "4. ÜNİTE: Liderlik (Takım kaptanlığı ve motivasyon)", "5. ÜNİTE: Dünya Sporları (Kriket, beyzbol gibi farklı branşlar)", "6. ÜNİTE: Sınav Kaygısı ve Hareket (Egzersizin ders başarısına etkisi)", "7. ÜNİTE: Atatürk ve Spor (Cumhuriyet dönemi spor hamleleri)", "8. ÜNİTE: Kariyer Planlama (Spor liseleri ve sporun geleceği)"],`,
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Müsabaka Yönetimi (Hakemlik işaretleri ve oyun yönetimi)", "2. ÜNİTE: Taktik Geliştirme (Karmaşık oyun stratejileri)", "3. ÜNİTE: Bireysel Gelişim (Kişisel fiziksel uygunluk karnesi)", "4. ÜNİTE: Liderlik (Takım kaptanlığı ve motivasyon)", "5. ÜNİTE: Dünya Sporları (Kriket, beyzbol gibi farklı branşlar)", "6. ÜNİTE: Sınav Kaygısı ve Hareket (Egzersizin ders başarısına etkisi)", "7. ÜNİTE: Atatürk ve Spor (Cumhuriyet dönemi spor hamleleri)", "8. ÜNİTE: Kariyer Planlama (Spor liseleri ve sporun geleceği)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Metin Tabanlı Programlama (Python programlama diline geçiş)", "2. ÜNİTE: Değişkenler ve Giriş-Çıkış (Python'da input ve print)", "3. ÜNİTE: Kontrol Yapıları (If-Elif-Else yapıları)", "4. ÜNİTE: Döngüler (For ve While döngüleri)", "5. ÜNİTE: Robotik Kodlama (Arduino kartı ve bileşenleri)", "6. ÜNİTE: Sensör Uygulamaları (Mesafe ve ışık sensörü kullanımı)", "7. ÜNİTE: Yapay Zeka ve Gelecek (ChatGPT ve benzeri sistemlerin mantığı)", "8. ÜNİTE: Bilişim Meslekleri (Geleceğin iş dünyasına hazırlık)"],`
    ],
    '9': [
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Yaşam Boyu Spor (Düzenli fiziksel aktivite felsefesi)", "2. ÜNİTE: Bireysel Sporlar (Tenis veya yüzme (teknik analiz))", "3. ÜNİTE: Takım Sporları (Branşa özgü derinleşme)", "4. ÜNİTE: Anatomi ve Hareket (Kas ve iskelet sisteminin sporla ilişkisi)", "5. ÜNİTE: Fizyolojik Uygunluk (Antrenman nabzı ve toparlanma süreci)", "6. ÜNİTE: Spor Etiği (Profesyonellik ve şike ile mücadele)", "7. ÜNİTE: Milli Kimlik ve Spor (Uluslararası arenada Türkiye)", "8. ÜNİTE: Dijitalleşen Spor (E-spor ve sanal antrenmanlar)"],`,
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Yaşam Boyu Spor (Düzenli fiziksel aktivite felsefesi)", "2. ÜNİTE: Bireysel Sporlar (Tenis veya yüzme (teknik analiz))", "3. ÜNİTE: Takım Sporları (Branşa özgü derinleşme)", "4. ÜNİTE: Anatomi ve Hareket (Kas ve iskelet sisteminin sporla ilişkisi)", "5. ÜNİTE: Fizyolojik Uygunluk (Antrenman nabzı ve toparlanma süreci)", "6. ÜNİTE: Spor Etiği (Profesyonellik ve şike ile mücadele)", "7. ÜNİTE: Milli Kimlik ve Spor (Uluslararası arenada Türkiye)", "8. ÜNİTE: Dijitalleşen Spor (E-spor ve sanal antrenmanlar)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Bilgi İşlemisel Düşünme (Karmaşık sorunların modellenmesi)", "2. ÜNİTE: Gelişmiş Algoritmalar (Sözde kod (Pseudocode) yazımı)", "3. ÜNİTE: Python ile Programlama - I (Temel söz dizimi ve operatörler)", "4. ÜNİTE: Listeler ve Koleksiyonlar (Diziler ve veri saklama yöntemleri)", "5. ÜNİTE: Dijital Okuryazarlık (Dijital içerik üretimi ve yönetimi)", "6. ÜNİTE: Ağ Protokolleri (HTTP, FTP, IP kavramları)", "7. ÜNİTE: Veri Güvenliği ve Gizlilik (Şifreleme (Kriptoloji) temelleri)", "8. ÜNİTE: Bilişim ve Girişimcilik (Startup kültürü ve dijital pazarlama)"],`
    ],
    '10': [
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Halk Dansları (Koreografi oluşturma ve sahneleme)", "2. ÜNİTE: Savunma Sporları (Öz savunma teknikleri ve felsefesi)", "3. ÜNİTE: Antrenman Bilgisi (Set, tekrar ve dinlenme kavramları)", "4. ÜNİTE: Sporda İlk Yardım (Turnike, pansuman ve taşıma teknikleri)", "5. ÜNİTE: Beslenme ve Performans (Ergojenik yardımcılar ve su dengesi)", "6. ÜNİTE: Dünya Kupaları (Büyük spor organizasyonlarının yapısı)", "7. ÜNİTE: Sporda Şiddet (Holiganizm ve önleme yolları)", "8. ÜNİTE: Tören ve Protokol (Resmi kutlama ve tören yönetimi)"],`,
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Halk Dansları (Koreografi oluşturma ve sahneleme)", "2. ÜNİTE: Savunma Sporları (Öz savunma teknikleri ve felsefesi)", "3. ÜNİTE: Antrenman Bilgisi (Set, tekrar ve dinlenme kavramları)", "4. ÜNİTE: Sporda İlk Yardım (Turnike, pansuman ve taşıma teknikleri)", "5. ÜNİTE: Beslenme ve Performans (Ergojenik yardımcılar ve su dengesi)", "6. ÜNİTE: Dünya Kupaları (Büyük spor organizasyonlarının yapısı)", "7. ÜNİTE: Sporda Şiddet (Holiganizm ve önleme yolları)", "8. ÜNİTE: Tören ve Protokol (Resmi kutlama ve tören yönetimi)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Python ile Programlama - II (Fonksiyonlar ve parametreler)", "2. ÜNİTE: Modüler Programlama (Kütüphane kullanımı ve oluşturma)", "3. ÜNİTE: Veritabanı Sistemleri (SQL sorguları ve tablo yapıları)", "4. ÜNİTE: Arayüz Tasarımı (Tkinter veya PyQt ile pencereli uygulamalar)", "5. ÜNİTE: Yazılım Yaşam Döngüsü (Tasarım modelleri ve test süreçleri)", "6. ÜNİTE: Mobil Uygulama Geliştirme (Flutter veya React Native temelleri)", "7. ÜNİTE: Veri Görselleştirme (Matplotlib ile grafik çizimi)", "8. ÜNİTE: Blockchain ve Kripto (Dağıtık defter teknolojisi)"],`
    ],
    '11': [
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Spor Yönetimi (Okul içi turnuva organizasyonu)", "2. ÜNİTE: Kuvvet Antrenmanları (İzometrik ve izotonik egzersizler)", "3. ÜNİTE: Rekreasyon Bilimi (Boş zamanların aktif değerlendirilmesi)", "4. ÜNİTE: Spor Psikolojisi (Galibiyet ve mağlubiyet psikolojisi)", "5. ÜNİTE: Doğa ve Macera Sporları (Kampçılık ve dağcılık temelleri)", "6. ÜNİTE: Spor Sosyolojisi (Sporun barışa ve demokrasiye katkısı)", "7. ÜNİTE: Türkiye'de Spor Kurumları (Gençlik ve Spor Bakanlığı ve federasyonlar)", "8. ÜNİTE: Geleceğin Sporları (Yeni trendler ve spor teknolojileri)"],`,
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Spor Yönetimi (Okul içi turnuva organizasyonu)", "2. ÜNİTE: Kuvvet Antrenmanları (İzometrik ve izotonik egzersizler)", "3. ÜNİTE: Rekreasyon Bilimi (Boş zamanların aktif değerlendirilmesi)", "4. ÜNİTE: Spor Psikolojisi (Galibiyet ve mağlubiyet psikolojisi)", "5. ÜNİTE: Doğa ve Macera Sporları (Kampçılık ve dağcılık temelleri)", "6. ÜNİTE: Spor Sosyolojisi (Sporun barışa ve demokrasiye katkısı)", "7. ÜNİTE: Türkiye'de Spor Kurumları (Gençlik ve Spor Bakanlığı ve federasyonlar)", "8. ÜNİTE: Geleceğin Sporları (Yeni trendler ve spor teknolojileri)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Nesne Yönelimli Programlama (OOP) (Class, Object, Inheritance)", "2. ÜNİTE: Web Frameworks (Django veya Flask ile arka yüz (Backend))", "3. ÜNİTE: Sunucu Teknolojileri (Linux komut satırı ve sunucu kurulumu)", "4. ÜNİTE: Siber Güvenlik - İleri (Sızma testleri ve savunma stratejileri)", "5. ÜNİTE: Yapay Zeka ve Makine Öğrenmesi (Scikit-learn ile modelleme)", "6. ÜNİTE: Görüntü İşleme (OpenCV ile görsel analiz)", "7. ÜNİTE: Büyük Veri Analizi (Pandas kütüphanesi ile veri işleme)", "8. ÜNİTE: Bilişim Proje Yönetimi (Agile ve Scrum çalışma prensipleri)"],`
    ],
    '12': [
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Meslek Tanıtımı (BESYO, SBF ve antrenörlük eğitimi)", "2. ÜNİTE: Sürdürülebilir Spor (Yeşil stadyumlar ve ekolojik etkinlikler)", "3. ÜNİTE: Engelliler İçin Egzersiz (Adaptif spor modelleri)", "4. ÜNİTE: Spor Ekonomisi (Sponsorluk ve profesyonel spor endüstrisi)", "5. ÜNİTE: İleri Düzey Performans (Kişisel hedeflere yönelik uzmanlaşma)", "6. ÜNİTE: Zihinsel Antrenman (Görselleştirme ve motivasyon teknikleri)", "7. ÜNİTE: Global Spor Sorunları (İnsan hakları ve sporda ayrımcılık)", "8. ÜNİTE: Yaşam Boyu Sağlık Rehberi (Mezuniyet sonrası aktif yaşam planı)"],`,
        `    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Meslek Tanıtımı (BESYO, SBF ve antrenörlük eğitimi)", "2. ÜNİTE: Sürdürülebilir Spor (Yeşil stadyumlar ve ekolojik etkinlikler)", "3. ÜNİTE: Engelliler İçin Egzersiz (Adaptif spor modelleri)", "4. ÜNİTE: Spor Ekonomisi (Sponsorluk ve profesyonel spor endüstrisi)", "5. ÜNİTE: İleri Düzey Performans (Kişisel hedeflere yönelik uzmanlaşma)", "6. ÜNİTE: Zihinsel Antrenman (Görselleştirme ve motivasyon teknikleri)", "7. ÜNİTE: Global Spor Sorunları (İnsan hakları ve sporda ayrımcılık)", "8. ÜNİTE: Yaşam Boyu Sağlık Rehberi (Mezuniyet sonrası aktif yaşam planı)"],\n    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Yapay Sinir Ağları (Derin öğrenme ve Keras/TensorFlow)", "2. ÜNİTE: Doğal Dil İşleme (NLP) (Metinlerin bilgisayarca anlamlandırılması)", "3. ÜNİTE: Sanal ve Artırılmış Gerçeklik (Unity ile 3D uygulama geliştirme)", "4. ÜNİTE: Gömülü Sistemler (Raspberry Pi ile Linux tabanlı projeler)", "5. ÜNİTE: Akıllı Şehirler ve IoT (Şehir yönetimi ve sensör ağları)", "6. ÜNİTE: Finansal Teknolojiler (Dijital bankacılık ve güvenli ödeme)", "7. ÜNİTE: Bilişim ve Etik Sorunlar (Transhümanizm ve AI etiği)", "8. ÜNİTE: Bitirme Projesi (Yıl sonu dijital ürün tasarımı ve sunumu)"],`
    ]
};

// We will split by lines and replace exact matches
let lines = content.split(/\\r?\\n/);

Object.keys(additions).forEach(grade => {
    let [searchFor, replaceWith] = additions[grade];
    let inserted = false;
    for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim() === searchFor.trim() && !inserted) {
            lines[i] = replaceWith;
            inserted = true;
        }
    }
});

// Write to file
fs.writeFileSync('src/curriculum.js', lines.join('\\n'));
