const fs = require('fs');
let content = fs.readFileSync('src/curriculum.js', 'utf8');

const additions = {
    '1': [
        `    'Hayat Bilgisi': ["1. ÜNİTE: Okulumuzda Hayat (Tanışma, okul kuralları ve çevre)", "2. ÜNİTE: Evimizde Hayat (Aile içi ilişkiler ve görevler)", "3. ÜNİTE: Sağlıklı Hayat (Kişisel temizlik ve beslenme)", "4. ÜNİTE: Güvenli Hayat (Okul yolu, trafik ve evdeki güvenlik)", "5. ÜNİTE: Ülkemizde Hayat (Yaşadığımız yer, bayrak ve Atatürk)", "6. ÜNİTE: Doğada Hayat (Mevsimler, hayvanlar ve bitkiler)"],`,
        `    'Hayat Bilgisi': ["1. ÜNİTE: Okulumuzda Hayat (Tanışma, okul kuralları ve çevre)", "2. ÜNİTE: Evimizde Hayat (Aile içi ilişkiler ve görevler)", "3. ÜNİTE: Sağlıklı Hayat (Kişisel temizlik ve beslenme)", "4. ÜNİTE: Güvenli Hayat (Okul yolu, trafik ve evdeki güvenlik)", "5. ÜNİTE: Ülkemizde Hayat (Yaşadığımız yer, bayrak ve Atatürk)", "6. ÜNİTE: Doğada Hayat (Mevsimler, hayvanlar ve bitkiler)"],\n    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Okuluma Merhaba (Okul bahçesi ve güvenli oyun alanları)", "2. ÜNİTE: Vücudumu Tanıyorum (Temel anatomik bölgeler ve hareket kabiliyeti)", "3. ÜNİTE: Temel Hareketler - I (Yer değiştirme (koşma, galop, sıçrama))", "4. ÜNİTE: Temel Hareketler - II (Dengeleme (eğilme, esneme, dönme))", "5. ÜNİTE: Nesne Kontrolü - I (Top yuvarlama, durdurma ve atma)", "6. ÜNİTE: Oyun Dünyası (Basit kurallı sınıf ve bahçe oyunları)", "7. ÜNİTE: Kişisel Bakım (Spor sonrası temizlik ve düzen)", "8. ÜNİTE: Sağlıklı Beslenme (Sporcu öğünü ve su tüketimi)"],`
    ],
    '2': [
        `    'İngilizce': ["1. TEMA: Interactive Greeting (Etkileşimli Selamlaşma)", "2. TEMA: My Immediate Environment (Yakın Çevrem - Okul ve Sınıf)", "3. TEMA: Numbers in My Life (Hayatımdaki Sayılar)", "4. TEMA: My Body and Actions (Vücudum ve Hareketler)", "5. TEMA: Colors of Nature (Doğanın Renkleri)", "6. TEMA: My Family and Friends (Ailem ve Arkadaşlarım)", "7. TEMA: Daily Activities (Günlük Etkinlikler ve Oyunlar)", "8. TEMA: Animals Around Us (Çevremizdeki Hayvanlar)"],`,
        `    'İngilizce': ["1. TEMA: Interactive Greeting (Etkileşimli Selamlaşma)", "2. TEMA: My Immediate Environment (Yakın Çevrem - Okul ve Sınıf)", "3. TEMA: Numbers in My Life (Hayatımdaki Sayılar)", "4. TEMA: My Body and Actions (Vücudum ve Hareketler)", "5. TEMA: Colors of Nature (Doğanın Renkleri)", "6. TEMA: My Family and Friends (Ailem ve Arkadaşlarım)", "7. TEMA: Daily Activities (Günlük Etkinlikler ve Oyunlar)", "8. TEMA: Animals Around Us (Çevremizdeki Hayvanlar)"],\n    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Hareketli Yaşam (Düzenli egzersizin vücuda etkileri)", "2. ÜNİTE: Kombine Hareketler (Koşarken nesne taşıma ve yön değiştirme)", "3. ÜNİTE: Eşli Oyunlar (Arkadaşıyla yardımlaşarak hareket etme)", "4. ÜNİTE: Nesne Kontrolü - II (Ayakla top sürme ve hedef vurma)", "5. ÜNİTE: Ritim ve Müzik (El çırpma ve tempo eşliğinde yürüyüş)", "6. ÜNİTE: Dikkat ve Koordinasyon (Tepki hızı gerektiren eğitsel oyunlar)", "7. ÜNİTE: Doğa Bilinci (Açık hava etkinlikleri ve çevre temizliği)", "8. ÜNİTE: Güvenli Hareket (Spor ekipmanlarını doğru kullanma)"],`
    ],
    '3': [
        `    'İngilizce': ["1. TEMA: Meeting People (İnsanlarla Tanışma)", "2. TEMA: My World at School (Okuldaki Dünyam)", "3. TEMA: People I Love (Sevdiğim İnsanlar)", "4. TEMA: My Feelings (Duygularım)", "5. TEMA: My House and Home (Evim ve Yaşam Alanım)", "6. TEMA: At the Playground (Parkta ve Oyun Alanında)", "7. TEMA: World of Nature (Doğa Dünyası)", "8. TEMA: Transportation and City (Ulaşım ve Şehir)"],`,
        `    'İngilizce': ["1. TEMA: Meeting People (İnsanlarla Tanışma)", "2. TEMA: My World at School (Okuldaki Dünyam)", "3. TEMA: People I Love (Sevdiğim İnsanlar)", "4. TEMA: My Feelings (Duygularım)", "5. TEMA: My House and Home (Evim ve Yaşam Alanım)", "6. TEMA: At the Playground (Parkta ve Oyun Alanında)", "7. TEMA: World of Nature (Doğa Dünyası)", "8. TEMA: Transportation and City (Ulaşım ve Şehir)"],\n    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Hareket Kavramları (Hareketin hızı, yönü ve alanı (uzamsal farkındalık))", "2. ÜNİTE: Geleneksel Oyunlar - I (Unutulmaya yüz tutmuş sokak oyunları)", "3. ÜNİTE: Çabukluk ve Çeviklik (İstasyon çalışmaları ve engelli parkurlar)", "4. ÜNİTE: Takım Ruhu (Grup içi iletişim ve yardımlaşma oyunları)", "5. ÜNİTE: Esneklik ve Denge (Statik ve dinamik denge çalışmaları)", "6. ÜNİTE: Ritmik Adımlar (Basit halk oyunları adımları)", "7. ÜNİTE: Vücut Yönetimi (Kendi ağırlığıyla yapılan temel egzersizler)", "8. ÜNİTE: Fair-Play Giriş (Kazanma ve kaybetmeyi kabullenme)"],`
    ],
    '4': [
        `    'Din Kültürü ve Ahlak Bilgisi': ["1. ÜNİTE: Günlük Hayattaki Dini İfadeler (Selamlaşma, dua, şükür ifadeleri)", "2. ÜNİTE: İslam’ı Tanıyalım (İslam’ın şartları ve imanın şartları)", "3. ÜNİTE: Adap ve Nezaket (Konuşma, yemek ve sosyal yaşam adabı)", "4. ÜNİTE: Hz. Muhammed’i Tanıyalım (Ailesi ve çocukluk yılları)", "5. ÜNİTE: Din ve Etik (Doğruluk, güvenilirlik ve sevgi)"],`,
        `    'Din Kültürü ve Ahlak Bilgisi': ["1. ÜNİTE: Günlük Hayattaki Dini İfadeler (Selamlaşma, dua, şükür ifadeleri)", "2. ÜNİTE: İslam’ı Tanıyalım (İslam’ın şartları ve imanın şartları)", "3. ÜNİTE: Adap ve Nezaket (Konuşma, yemek ve sosyal yaşam adabı)", "4. ÜNİTE: Hz. Muhammed’i Tanıyalım (Ailesi ve çocukluk yılları)", "5. ÜNİTE: Din ve Etik (Doğruluk, güvenilirlik ve sevgi)"],\n    'Oyun ve Fiziki Etkinlikler': ["1. ÜNİTE: Branş Hazırlık - I (Basketbol ve voleybol temel mekanikleri)", "2. ÜNİTE: Branş Hazırlık - II (Futbol ve hentbol temel mekanikleri)", "3. ÜNİTE: Strateji ve Taktik (Oyun içinde yer tutma ve paslaşma)", "4. ÜNİTE: Geleneksel Oyunlar - II (Yöresel oyunlar ve kuralları)", "5. ÜNİTE: Fiziksel Uygunluk (Boy, kilo ve nabız ölçüm takibi)", "6. ÜNİTE: İlkyardım Bilgisi (Küçük yaralanmalarda yapılacaklar)", "7. ÜNİTE: Milli Bayramlar (Tören düzeni ve bayram kutlamaları)", "8. ÜNİTE: Spor Etiği (Kurallara bağlılık ve rakibe saygı)"],`
    ],
    '5': [
        `    'İngilizce': ["1. TEMA: Hello & Socializing (Selamlaşma ve Sosyalleşme)", "2. TEMA: My Town & Places (Şehrim ve Mekanlar)", "3. TEMA: Games & Sportsmanship (Oyunlar ve Sporcu Ruhu)", "4. TEMA: Daily Routines & Time (Günlük Planlar ve Zaman Yönetimi)", "5. TEMA: Health & Wellness (Sağlık ve Esenlik)", "6. TEMA: Media & Entertainment (Medya ve Eğlence - Filmler)", "7. TEMA: Social Gatherings (Social Buluşmalar ve Partiler)", "8. TEMA: Physical Activities (Fiziksel Aktiviteler ve Doğa)", "9. TEMA: Animal Rights & Care (Hayvan Hakları ve Bakımı)", "10. TEMA: Cultural Celebrations (Kültürel Kutlamalar ve Festivaller)"],`,
        `    'İngilizce': ["1. TEMA: Hello & Socializing (Selamlaşma ve Sosyalleşme)", "2. TEMA: My Town & Places (Şehrim ve Mekanlar)", "3. TEMA: Games & Sportsmanship (Oyunlar ve Sporcu Ruhu)", "4. TEMA: Daily Routines & Time (Günlük Planlar ve Zaman Yönetimi)", "5. TEMA: Health & Wellness (Sağlık ve Esenlik)", "6. TEMA: Media & Entertainment (Medya ve Eğlence - Filmler)", "7. TEMA: Social Gatherings (Social Buluşmalar ve Partiler)", "8. TEMA: Physical Activities (Fiziksel Aktiviteler ve Doğa)", "9. TEMA: Animal Rights & Care (Hayvan Hakları ve Bakımı)", "10. TEMA: Cultural Celebrations (Kültürel Kutlamalar ve Festivaller)"],\n    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Hareket Eğitimi (Temel duruşlar ve dizilişler)", "2. ÜNİTE: Atletizm (Koşu teknikleri ve bayrak yarışı)", "3. ÜNİTE: Voleybol (Parmak pas ve manşet pas temelleri)", "4. ÜNİTE: Basketbol (Top sürme ve şut mekaniği)", "5. ÜNİTE: Jimnastik (Öne ve arkaya takla, denge çalışmaları)", "6. ÜNİTE: Fiziksel Etkinlik (Haftalık egzersiz planı oluşturma)", "7. ÜNİTE: Spor Kültürü (Olimpiyat halkalarının anlamı ve tarihi)", "8. ÜNİTE: Beslenme Okuryazarlığı (Kalori hesabı ve paketli gıdalar)"],`
    ],
    '6': [
        `    'İngilizce': ["1. TEMA: Life & Routine (Hayat ve Rutin)", "2. TEMA: Yummy Breakfast (Beslenme Alışkanlıkları)", "3. TEMA: Downtown & City Life (Şehir Merkezi ve Yaşam)", "4. TEMA: Weather & Emotions (Hava Durumu ve Duygular)", "5. TEMA: At the Fair (Panayır ve Eğlence)", "6. TEMA: Occupations (Meslekler ve Gelecek)", "7. TEMA: Holidays & Travel (Tatiller ve Gezi)", "8. TEMA: Bookworms (Kitap Dostları/Kütüphane)", "9. TEMA: Saving the Planet (Gezegeni Kurtarmak)", "10. TEMA: Democracy (Demokrasi ve Katılım)"],`,
        `    'İngilizce': ["1. TEMA: Life & Routine (Hayat ve Rutin)", "2. TEMA: Yummy Breakfast (Beslenme Alışkanlıkları)", "3. TEMA: Downtown & City Life (Şehir Merkezi ve Yaşam)", "4. TEMA: Weather & Emotions (Hava Durumu ve Duygular)", "5. TEMA: At the Fair (Panayır ve Eğlence)", "6. TEMA: Occupations (Meslekler ve Gelecek)", "7. TEMA: Holidays & Travel (Tatiller ve Gezi)", "8. TEMA: Bookworms (Kitap Dostları/Kütüphane)", "9. TEMA: Saving the Planet (Gezegeni Kurtarmak)", "10. TEMA: Democracy (Demokrasi ve Katılım)"],\n    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Hentbol (Temel atışlar ve kale savunması)", "2. ÜNİTE: Masa Tenisi (Raket tutuşu ve servis çeşitleri)", "3. ÜNİTE: Badminton (Vuruş teknikleri ve saha çizgileri)", "4. ÜNİTE: Dayanıklılık (Orta mesafe koşuları ve nefes kontrolü)", "5. ÜNİTE: Halk Oyunları (Bölgesel oyunlar ve ritim çalışması)", "6. ÜNİTE: Öz Disiplin (Antrenman disiplini ve devamlılık)", "7. ÜNİTE: Engelliler ve Spor (Paralimpik branşları tanıma)", "8. ÜNİTE: Teknoloji ve Spor (Adım sayar ve mobil sağlık uygulamaları)"],`
    ],
    '7': [
        `    'Din Kültürü ve Ahlak Bilgisi': ["1. ÜNİTE: Melek ve Ahiret İnancı (Gayb alemi ve ahiret hayatının aşamaları)", "2. ÜNİTE: Hac ve Kurban (İbadetlerin yapılışı ve toplumsal dayanışma)", "3. ÜNİTE: Ahlaki Davranışlar (Yardımseverlik, sabır ve dürüstlük)", "4. ÜNİTE: Hz. Muhammed’in Erdemli Davranışları (Adaleti ve istişaresi)", "5. ÜNİTE: İslam Düşüncesinde Yorumlar (Mezhepler ve farklı yorum biçimleri)"],`,
        `    'Din Kültürü ve Ahlak Bilgisi': ["1. ÜNİTE: Melek ve Ahiret İnancı (Gayb alemi ve ahiret hayatının aşamaları)", "2. ÜNİTE: Hac ve Kurban (İbadetlerin yapılışı ve toplumsal dayanışma)", "3. ÜNİTE: Ahlaki Davranışlar (Yardımseverlik, sabır ve dürüstlük)", "4. ÜNİTE: Hz. Muhammed’in Erdemli Davranışları (Adaleti ve istişaresi)", "5. ÜNİTE: İslam Düşüncesinde Yorumlar (Mezhepler ve farklı yorum biçimleri)"],\n    'Beden Eğitimi ve Spor': ["1. ÜNİTE: İleri Voleybol (Servis atma ve oyun kuralları)", "2. ÜNİTE: İleri Basketbol (Turnike ve savunma çeşitleri)", "3. ÜNİTE: Oryantiring (Harita okuma ve doğada yön bulma)", "4. ÜNİTE: Kuvvet ve Esneklik (Direnç bantları ile çalışma)", "5. ÜNİTE: Doping ve Zararları (Temiz spor bilinci)", "6. ÜNİTE: Spor Tarihi (Türk sporunun efsane isimleri)", "7. ÜNİTE: Zihin ve Spor (Odaklanma ve stres yönetimi)", "8. ÜNİTE: Sosyal Sorumluluk (Sporla toplumsal farkındalık projeleri)"],`
    ],
    '8': [
        `    'Din Kültürü ve Ahlak Bilgisi': ["1. ÜNİTE: Kader İnancı (Kader, kaza, tevekkül ve rızık kavramları)", "2. ÜNİTE: Zekât ve Sadaka (İnfak kültürü ve sosyal yardımlaşma)", "3. ÜNİTE: Din ve Hayat (Dinin temel gayeleri (can, mal, akıl, nesil, din emniyeti))", "4. ÜNİTE: Hz. Muhammed’in Örnekliği (Merhameti ve azmi)", "5. ÜNİTE: Kur’an-ı Kerim ve Özellikleri (Muhtevası ve rehberliği)"],`,
        `    'Din Kültürü ve Ahlak Bilgisi': ["1. ÜNİTE: Kader İnancı (Kader, kaza, tevekkül ve rızık kavramları)", "2. ÜNİTE: Zekât ve Sadaka (İnfak kültürü ve sosyal yardımlaşma)", "3. ÜNİTE: Din ve Hayat (Dinin temel gayeleri (can, mal, akıl, nesil, din emniyeti))", "4. ÜNİTE: Hz. Muhammed’in Örnekliği (Merhameti ve azmi)", "5. ÜNİTE: Kur’an-ı Kerim ve Özellikleri (Muhtevası ve rehberliği)"],\n    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Müsabaka Yönetimi (Hakemlik işaretleri ve oyun yönetimi)", "2. ÜNİTE: Taktik Geliştirme (Karmaşık oyun stratejileri)", "3. ÜNİTE: Bireysel Gelişim (Kişisel fiziksel uygunluk karnesi)", "4. ÜNİTE: Liderlik (Takım kaptanlığı ve motivasyon)", "5. ÜNİTE: Dünya Sporları (Kriket, beyzbol gibi farklı branşlar)", "6. ÜNİTE: Sınav Kaygısı ve Hareket (Egzersizin ders başarısına etkisi)", "7. ÜNİTE: Atatürk ve Spor (Cumhuriyet dönemi spor hamleleri)", "8. ÜNİTE: Kariyer Planlama (Spor liseleri ve sporun geleceği)"],`
    ],
    '9': [
        `    'İngilizce': ["1. TEMA: Studying Abroad (Yurt Dışında Eğitim ve Tanışma)", "2. TEMA: My Environment (Çevrem, Şehrim ve Mekanlar)", "3. TEMA: Movies (Sinema, Türler ve Eleştiri)", "4. TEMA: Human Rights (İnsan Hakları ve Adalet - Maarif Modeli Değer Odağı)", "5. TEMA: Inspirational People (İlham Veren Kişiler ve Biyografiler)", "6. TEMA: Bridging Cultures (Kültürlerarası Köprüler ve Gelenekler)", "7. TEMA: World Heritage (Dünya Mirası ve Tarihi Yerler)", "8. TEMA: Emergency and Health (Acil Durumlar ve Sağlık Bilinci)", "9. TEMA: Invitations and Celebrations (Davetler ve Sosyal Etkinlikler)", "10. TEMA: Television and Social Media (Dijital Medya ve İletişim)"],`,
        `    'İngilizce': ["1. TEMA: Studying Abroad (Yurt Dışında Eğitim ve Tanışma)", "2. TEMA: My Environment (Çevrem, Şehrim ve Mekanlar)", "3. TEMA: Movies (Sinema, Türler ve Eleştiri)", "4. TEMA: Human Rights (İnsan Hakları ve Adalet - Maarif Modeli Değer Odağı)", "5. TEMA: Inspirational People (İlham Veren Kişiler ve Biyografiler)", "6. TEMA: Bridging Cultures (Kültürlerarası Köprüler ve Gelenekler)", "7. TEMA: World Heritage (Dünya Mirası ve Tarihi Yerler)", "8. TEMA: Emergency and Health (Acil Durumlar ve Sağlık Bilinci)", "9. TEMA: Invitations and Celebrations (Davetler ve Sosyal Etkinlikler)", "10. TEMA: Television and Social Media (Dijital Medya ve İletişim)"],\n    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Yaşam Boyu Spor (Düzenli fiziksel aktivite felsefesi)", "2. ÜNİTE: Bireysel Sporlar (Tenis veya yüzme (teknik analiz))", "3. ÜNİTE: Takım Sporları (Branşa özgü derinleşme)", "4. ÜNİTE: Anatomi ve Hareket (Kas ve iskelet sisteminin sporla ilişkisi)", "5. ÜNİTE: Fizyolojik Uygunluk (Antrenman nabzı ve toparlanma süreci)", "6. ÜNİTE: Spor Etiği (Profesyonellik ve şike ile mücadele)", "7. ÜNİTE: Milli Kimlik ve Spor (Uluslararası arenada Türkiye)", "8. ÜNİTE: Dijitalleşen Spor (E-spor ve sanal antrenmanlar)"],`
    ],
    '10': [
        `    'İngilizce': ["1. TEMA: School Life (Okul Yaşamı ve Rutinler)", "2. TEMA: Plans and Predictions (Gelecek Planları ve Tahminler)", "3. TEMA: Legendary Figures (Efsanevi Figürler ve Tarihi Kahramanlar)", "4. TEMA: Traditions (Gelenekler ve Kültürel Aktarım)", "5. TEMA: Travel (Seyahat ve Gezi Kültürü)", "6. TEMA: Helpful Tips (Faydalı İpuçları ve Tavsiyeler)", "7. TEMA: Food and Festivals (Yemek Kültürü ve Festivaller)", "8. TEMA: Digital Era (Dijital Çağ ve Teknoloji)", "9. TEMA: Modern Heroes (Modern Kahramanlar ve İyilik Hareketleri)", "10. TEMA: Shopping (Alışveriş ve Bilinçli Tüketim)"],`,
        `    'İngilizce': ["1. TEMA: School Life (Okul Yaşamı ve Rutinler)", "2. TEMA: Plans and Predictions (Gelecek Planları ve Tahminler)", "3. TEMA: Legendary Figures (Efsanevi Figürler ve Tarihi Kahramanlar)", "4. TEMA: Traditions (Gelenekler ve Kültürel Aktarım)", "5. TEMA: Travel (Seyahat ve Gezi Kültürü)", "6. TEMA: Helpful Tips (Faydalı İpuçları ve Tavsiyeler)", "7. TEMA: Food and Festivals (Yemek Kültürü ve Festivaller)", "8. TEMA: Digital Era (Dijital Çağ ve Teknoloji)", "9. TEMA: Modern Heroes (Modern Kahramanlar ve İyilik Hareketleri)", "10. TEMA: Shopping (Alışveriş ve Bilinçli Tüketim)"],\n    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Halk Dansları (Koreografi oluşturma ve sahneleme)", "2. ÜNİTE: Savunma Sporları (Öz savunma teknikleri ve felsefesi)", "3. ÜNİTE: Antrenman Bilgisi (Set, tekrar ve dinlenme kavramları)", "4. ÜNİTE: Sporda İlk Yardım (Turnike, pansuman ve taşıma teknikleri)", "5. ÜNİTE: Beslenme ve Performans (Ergojenik yardımcılar ve su dengesi)", "6. ÜNİTE: Dünya Kupaları (Büyük spor organizasyonlarının yapısı)", "7. ÜNİTE: Sporda Şiddet (Holiganizm ve önleme yolları)", "8. ÜNİTE: Tören ve Protokol (Resmi kutlama ve tören yönetimi)"],`
    ],
    '11': [
        `    'İngilizce': ["1. TEMA: Future Jobs (Geleceğin Meslekleri ve Kariyer)", "2. TEMA: Hobbies and Skills (Hobiler ve Yetenek Yönetimi)", "3. TEMA: Hard Times (Zor Zamanlar ve Dayanıklılık)", "4. TEMA: What a Coincidence! (Tesadüfler ve Anılar)", "5. TEMA: Back to the Past (Geçmişe Yolculuk)", "6. TEMA: Open Your Heart (Yardımlaşma ve Empati)", "7. TEMA: Facts about Turkey (Türkiye Hakkında Gerçekler ve Tanıtım)", "8. TEMA: Sports (Spor Etiği ve Sağlık)", "9. TEMA: My Friends (Dostluk ve Sosyal Bağlar)", "10. TEMA: Values and Norms (Değerler ve Toplumsal Kurallar)"],`,
        `    'İngilizce': ["1. TEMA: Future Jobs (Geleceğin Meslekleri ve Kariyer)", "2. TEMA: Hobbies and Skills (Hobiler ve Yetenek Yönetimi)", "3. TEMA: Hard Times (Zor Zamanlar ve Dayanıklılık)", "4. TEMA: What a Coincidence! (Tesadüfler ve Anılar)", "5. TEMA: Back to the Past (Geçmişe Yolculuk)", "6. TEMA: Open Your Heart (Yardımlaşma ve Empati)", "7. TEMA: Facts about Turkey (Türkiye Hakkında Gerçekler ve Tanıtım)", "8. TEMA: Sports (Spor Etiği ve Sağlık)", "9. TEMA: My Friends (Dostluk ve Sosyal Bağlar)", "10. TEMA: Values and Norms (Değerler ve Toplumsal Kurallar)"],\n    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Spor Yönetimi (Okul içi turnuva organizasyonu)", "2. ÜNİTE: Kuvvet Antrenmanları (İzometrik ve izotonik egzersizler)", "3. ÜNİTE: Rekreasyon Bilimi (Boş zamanların aktif değerlendirilmesi)", "4. ÜNİTE: Spor Psikolojisi (Galibiyet ve mağlubiyet psikolojisi)", "5. ÜNİTE: Doğa ve Macera Sporları (Kampçılık ve dağcılık temelleri)", "6. ÜNİTE: Spor Sosyolojisi (Sporun barışa ve demokrasiye katkısı)", "7. ÜNİTE: Türkiye'de Spor Kurumları (Gençlik ve Spor Bakanlığı ve federasyonlar)", "8. ÜNİTE: Geleceğin Sporları (Yeni trendler ve spor teknolojileri)"],`
    ],
    '12': [
        `    'İngilizce': ["1. TEMA: Music (Müzik ve Duygular)", "2. TEMA: Friendship (Derin Dostluklar ve Güven)", "3. TEMA: Human Rights & Democracy (İnsan Hakları ve Demokrasi Kültürü)", "4. TEMA: Coming Soon (Yakın Gelecek ve Teknolojik Gelişmeler)", "5. TEMA: Psychology (Psikoloji ve İnsan Davranışı)", "6. TEMA: Favors (İyilik Yapma ve Sosyal Sorumluluk)", "7. TEMA: News and Media (Haber Analizi ve Medya Okuryazarlığı)", "8. TEMA: Alternative Energy (Alternatif Enerji ve Çevre Koruma)", "9. TEMA: Technology (İleri Teknoloji ve Yapay Zeka)", "10. TEMA: Manners (Görgü Kuralları ve Sosyal Etik)"],`,
        `    'İngilizce': ["1. TEMA: Music (Müzik ve Duygular)", "2. TEMA: Friendship (Derin Dostluklar ve Güven)", "3. TEMA: Human Rights & Democracy (İnsan Hakları ve Demokrasi Kültürü)", "4. TEMA: Coming Soon (Yakın Gelecek ve Teknolojik Gelişmeler)", "5. TEMA: Psychology (Psikoloji ve İnsan Davranışı)", "6. TEMA: Favors (İyilik Yapma ve Sosyal Sorumluluk)", "7. TEMA: News and Media (Haber Analizi ve Medya Okuryazarlığı)", "8. TEMA: Alternative Energy (Alternatif Enerji ve Çevre Koruma)", "9. TEMA: Technology (İleri Teknoloji ve Yapay Zeka)", "10. TEMA: Manners (Görgü Kuralları ve Sosyal Etik)"],\n    'Beden Eğitimi ve Spor': ["1. ÜNİTE: Meslek Tanıtımı (BESYO, SBF ve antrenörlük eğitimi)", "2. ÜNİTE: Sürdürülebilir Spor (Yeşil stadyumlar ve ekolojik etkinlikler)", "3. ÜNİTE: Engelliler İçin Egzersiz (Adaptif spor modelleri)", "4. ÜNİTE: Spor Ekonomisi (Sponsorluk ve profesyonel spor endüstrisi)", "5. ÜNİTE: İleri Düzey Performans (Kişisel hedeflere yönelik uzmanlaşma)", "6. ÜNİTE: Zihinsel Antrenman (Görselleştirme ve motivasyon teknikleri)", "7. ÜNİTE: Global Spor Sorunları (İnsan hakları ve sporda ayrımcılık)", "8. ÜNİTE: Yaşam Boyu Sağlık Rehberi (Mezuniyet sonrası aktif yaşam planı)"],`
    ]
};

// We will split by lines and replace exact matches
let lines = content.split(/\r?\n/);
let outputLines = [];

Object.keys(additions).forEach(grade => {
    let [searchFor, replaceWith] = additions[grade];
    let inserted = false;
    for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim() === searchFor.trim() && !inserted) {
            lines[i] = replaceWith;
            inserted = true;
        }
    }
});

// Write to file
fs.writeFileSync('src/curriculum.js', lines.join('\n'));
