const fs = require('fs');

let input = fs.readFileSync('src/curriculum.js', 'utf8');

const btyBlocks = {
    '1': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Bilişimle Tanışıyorum (Teknolojik araçlar ve kullanım alanları)", "2. ÜNİTE: Bilgisayarın Parçaları (Fare, klavye, ekran ve kasa fonksiyonları)", "3. ÜNİTE: Doğru Oturuş ve Sağlık (Ergonomi ve ekran mesafesi kuralları)", "4. ÜNİTE: Dijital Vatandaşlığa Giriş (İnternette nezaket (Netiket))", "5. ÜNİTE: Algoritma Dünyası (Adım adım talimat verme (Bilgisayarsız))", "6. ÜNİTE: Yön Komutları (Karakterleri hedefe ulaştırma oyunları)", "7. ÜNİTE: Çizim Araçları (Dijital ortamda ilk görsel tasarımlar)", "8. ÜNİTE: Güvenli İnternet (Özel bilgileri koruma ve yardım isteme)"],`,
    '2': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Teknoloji ve Ben (Günlük hayattaki dijital yardımcılarımız)", "2. ÜNİTE: Klavye ve Fare Kullanımı (Tuşların görevleri ve sürükle-bırak)", "3. ÜNİTE: Dosya ve Klasör (Bilgilerimizi nasıl saklarız?)", "4. ÜNİTE: Dijital Güvenlik (Güçlü şifre oluşturma yöntemleri)", "5. ÜNİTE: Döngüsel Algoritmalar (Tekrar eden işlerin mantığı)", "6. ÜNİTE: Bloklarla Kodlama (Basit bloklarla karakter yönetimi)", "7. ÜNİTE: İnternette Bilgi Arama (Görsel ve metin arama teknikleri)", "8. ÜNİTE: Medya Okuryazarlığı (Gördüğümüz her şey gerçek mi?)"],`,
    '3': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Bilişim Etiği (Telif hakları ve dijital paylaşım kuralları)", "2. ÜNİTE: İşletim Sistemleri (Windows, Android ve iOS dünyası)", "3. ÜNİTE: Bulut Depolama (Google Drive ve OneDrive kullanımı)", "4. ÜNİTE: Kelime İşlemci - I (Metin yazma, kalınlaştırma ve renklendirme)", "5. ÜNİTE: Algoritmik Düşünme (Problem çözme ve akış şeması mantığı)", "6. ÜNİTE: Scratch ile Kodlama (İlk animasyonumu yapıyorum)", "7. ÜNİTE: Siber Zorbalık (Dijital zorbalıkla baş etme yöntemleri)", "8. ÜNİTE: Robotlar Nasıl Çalışır? (Sensörler ve motorların görevi)"],`,
    '4': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Donanım ve Yazılım (Bilgisayarın iç birimleri (RAM, İşlemci, HDD))", "2. ÜNİTE: Arama Stratejileri (Doğru bilgiye hızlı ulaşma yöntemleri)", "3. ÜNİTE: Sunum Programları (Etkili slayt hazırlama teknikleri)", "4. ÜNİTE: Koşul Yapıları (\\"Eğer\\" ise mantığıyla karar verme)", "5. ÜNİTE: Hata Ayıklama (Kodlardaki yanlışları bulma (Debugging))", "6. ÜNİTE: Dijital Oyun Tasarımı (Kendi basit oyunumun kurallarını yazma)", "7. ÜNİTE: E-Okul ve E-Devlet (Dijital devlet hizmetlerini tanıma)", "8. ÜNİTE: Yapay Zeka Nedir? (Akıllı makineler nasıl öğrenir?)"],`,
    '5': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Bilişim Etiği ve Sosyal Medya (Dijital ayak izi ve mahremiyet)", "2. ÜNİTE: Siber Güvenlik (Virüsler, truva atları ve korunma)", "3. ÜNİTE: Bilgisayar Sistemleri (Giriş, çıkış ve depolama birimleri)", "4. ÜNİTE: Bilgisayar Ağları (Modemin yapısı ve internetin yayılımı)", "5. ÜNİTE: Problem Çözme Süreci (Analiz, tasarım ve uygulama)", "6. ÜNİTE: Algoritmalar ve Akış Şemaları (Standart sembollerle algoritma çizimi)", "7. ÜNİTE: Blok Tabanlı Programlama (Değişkenler ve veri türleri)", "8. ÜNİTE: Müzik ve Ses Düzenleme (Dijital ses dosyalarıyla çalışma)"],`,
    '6': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Bilişim Teknolojileri ve Değişim (Teknolojinin tarihsel gelişimi)", "2. ÜNİTE: Dijital Ortamda İş Birliği (Google Dokümanlar ile ortak çalışma)", "3. ÜNİTE: Hesaplama Çizelgeleri (Excel) (Satır, sütun ve hücre mantığı)", "4. ÜNİTE: Fonksiyonlar ve Formüller (Otomatik hesaplama araçları)", "5. ÜNİTE: Olay Yönetimi (Programlarda tetikleyici olaylar)", "6. ÜNİTE: Proje Geliştirme (Scratch ile kapsamlı bir uygulama sürec)", "7. ÜNİTE: Nesnelerin İnterneti (IoT) (Akıllı ev sistemleri)", "8. ÜNİTE: Bilişim Hukuku (İnternet suçları ve yaptırımlar)"],`,
    '7': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: 3B Tasarım ve Modelleme (Tinkercad ile üç boyutlu dünyalar)", "2. ÜNİTE: Grafik Tasarımı (Piksel ve vektör tabanlı görseller (Canva/GIMP))", "3. ÜNİTE: Web Tasarımına Giriş (HTML etiketleri ve yapı)", "4. ÜNİTE: Stil Sayfaları (CSS ile web sitesini renklendirme)", "5. ÜNİTE: Algoritma Analizi (En kısa yol ve verimlilik)", "6. ÜNİTE: Mobil Programlama (App Inventor ile mobil arayüz)", "7. ÜNİTE: Veri Madenciliği Giriş (Verilerin analiz edilmesi)", "8. ÜNİTE: Siber Tehdit Avcılığı (Phishing (Oltalama) ve korunma)"],`,
    '8': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Metin Tabanlı Programlama (Python programlama diline geçiş)", "2. ÜNİTE: Değişkenler ve Giriş-Çıkış (Python'da input ve print)", "3. ÜNİTE: Kontrol Yapıları (If-Elif-Else yapıları)", "4. ÜNİTE: Döngüler (For ve While döngüleri)", "5. ÜNİTE: Robotik Kodlama (Arduino kartı ve bileşenleri)", "6. ÜNİTE: Sensör Uygulamaları (Mesafe ve ışık sensörü kullanımı)", "7. ÜNİTE: Yapay Zeka ve Gelecek (ChatGPT ve benzeri sistemlerin mantığı)", "8. ÜNİTE: Bilişim Meslekleri (Geleceğin iş dünyasına hazırlık)"],`,
    '9': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Bilgi İşlemisel Düşünme (Karmaşık sorunların modellenmesi)", "2. ÜNİTE: Gelişmiş Algoritmalar (Sözde kod (Pseudocode) yazımı)", "3. ÜNİTE: Python ile Programlama - I (Temel söz dizimi ve operatörler)", "4. ÜNİTE: Listeler ve Koleksiyonlar (Diziler ve veri saklama yöntemleri)", "5. ÜNİTE: Dijital Okuryazarlık (Dijital içerik üretimi ve yönetimi)", "6. ÜNİTE: Ağ Protokolleri (HTTP, FTP, IP kavramları)", "7. ÜNİTE: Veri Güvenliği ve Gizlilik (Şifreleme (Kriptoloji) temelleri)", "8. ÜNİTE: Bilişim ve Girişimcilik (Startup kültürü ve dijital pazarlama)"],`,
    '10': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Python ile Programlama - II (Fonksiyonlar ve parametreler)", "2. ÜNİTE: Modüler Programlama (Kütüphane kullanımı ve oluşturma)", "3. ÜNİTE: Veritabanı Sistemleri (SQL sorguları ve tablo yapıları)", "4. ÜNİTE: Arayüz Tasarımı (Tkinter veya PyQt ile pencereli uygulamalar)", "5. ÜNİTE: Yazılım Yaşam Döngüsü (Tasarım modelleri ve test süreçleri)", "6. ÜNİTE: Mobil Uygulama Geliştirme (Flutter veya React Native temelleri)", "7. ÜNİTE: Veri Görselleştirme (Matplotlib ile grafik çizimi)", "8. ÜNİTE: Blockchain ve Kripto (Dağıtık defter teknolojisi)"],`,
    '11': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Nesne Yönelimli Programlama (OOP) (Class, Object, Inheritance)", "2. ÜNİTE: Web Frameworks (Django veya Flask ile arka yüz (Backend))", "3. ÜNİTE: Sunucu Teknolojileri (Linux komut satırı ve sunucu kurulumu)", "4. ÜNİTE: Siber Güvenlik - İleri (Sızma testleri ve savunma stratejileri)", "5. ÜNİTE: Yapay Zeka ve Makine Öğrenmesi (Scikit-learn ile modelleme)", "6. ÜNİTE: Görüntü İşleme (OpenCV ile görsel analiz)", "7. ÜNİTE: Büyük Veri Analizi (Pandas kütüphanesi ile veri işleme)", "8. ÜNİTE: Bilişim Proje Yönetimi (Agile ve Scrum çalışma prensipleri)"],`,
    '12': `    'Bilişim Teknolojileri ve Yazılım': ["1. ÜNİTE: Yapay Sinir Ağları (Derin öğrenme ve Keras/TensorFlow)", "2. ÜNİTE: Doğal Dil İşleme (NLP) (Metinlerin bilgisayarca anlamlandırılması)", "3. ÜNİTE: Sanal ve Artırılmış Gerçeklik (Unity ile 3D uygulama geliştirme)", "4. ÜNİTE: Gömülü Sistemler (Raspberry Pi ile Linux tabanlı projeler)", "5. ÜNİTE: Akıllı Şehirler ve IoT (Şehir yönetimi ve sensör ağları)", "6. ÜNİTE: Finansal Teknolojiler (Dijital bankacılık ve güvenli ödeme)", "7. ÜNİTE: Bilişim ve Etik Sorunlar (Transhümanizm ve AI etiği)", "8. ÜNİTE: Bitirme Projesi (Yıl sonu dijital ürün tasarımı ve sunumu)"],`
};

const artBlocks = {
    '1': `    'Görsel Sanatlar': ["1. ÜNİTE: Sanata Merhaba (Görsel sanatlar araç gereçlerini tanıma ve doğru kullanım)", "2. ÜNİTE: Nokta ve Çizgi (Çizgi çeşitleri ile temel yüzey çalışmaları)", "3. ÜNİTE: Ana Renkler (Kırmızı, sarı ve mavinin dünyası)", "4. ÜNİTE: Doğadaki Şekiller (Geometrik ve organik formları fark etme)", "5. ÜNİTE: Kes-Yapıştır (Kolaj) (Kağıt işleri ve basit kolaj uygulamaları)", "6. ÜNİTE: Kil ve Hamur (Üç boyutlu parmak çalışmaları)", "7. ÜNİTE: Müze Bilinci (Sanat eserlerine nasıl bakılır?)", "8. ÜNİTE: Özel Gün Kartları (Tebrik kartı tasarımı ve süsleme)"],`,
    '2': `    'Görsel Sanatlar': ["1. ÜNİTE: Renklerin Karışımı (Ara renkleri oluşturma (Turuncu, Yeşil, Mor))", "2. ÜNİTE: Doku Çalışmaları (Çizgisel ve gerçek doku örnekleri)", "3. ÜNİTE: Mekan ve Yerleşim (Kağıt üzerinde alt-üst, ön-arka kavramları)", "4. ÜNİTE: Portreye Giriş (Kendi yüzümüzü tanıyalım (Otoportre))", "5. ÜNİTE: Atıklarla Sanat (Geri dönüşüm malzemelerinden tasarım)", "6. ÜNİTE: Milli Bayramlarımız (Kutlama görselleri ve afiş hazırlama)", "7. ÜNİTE: Geleneksel Motifler (Basit Türk motifleri ve desenler)", "8. ÜNİTE: İz Bırakan Sanatçılar (Ünlü tabloları tanıma ve yorumlama)"],`,
    '3': `    'Görsel Sanatlar': ["1. ÜNİTE: Işık ve Gölge (Cisimlerin hacim kazanması)", "2. ÜNİTE: Sıcak ve Soğuk Renkler (Renklerin psikolojik etkileri)", "3. ÜNİTE: Baskı Sanatı - I (Patates, yaprak veya sünger baskısı)", "4. ÜNİTE: Figür Çizimi (İnsan vücudunun temel oranları)", "5. ÜNİTE: Kültürel Miras (Tarihi mekanları tanıma ve resmetme)", "6. ÜNİTE: Tasarım ve Fonksiyon (Günlük eşyaların estetiği)", "7. ÜNİTE: Maske Tasarımı (Kağıt tabaklardan üç boyutlu maskeler)", "8. ÜNİTE: Sanat Eleştirisi (Bir sanat eserini beğenme kriterleri)"],`,
    '4': `    'Görsel Sanatlar': ["1. ÜNİTE: Perspektife Giriş (Uzaklık ve yakınlık algısı)", "2. ÜNİTE: Tamamlayıcı Renkler (Kontrast renklerin kullanımı)", "3. ÜNİTE: Karikatür Dünyası (Abartı ve mizahın sanattaki yeri)", "4. ÜNİTE: Ebru Sanatı (Su üzerindeki renklerin dansı (Geleneksel sanatlar))", "5. ÜNİTE: Mimari Tasarım (Hayalimdeki ev veya okul modeli)", "6. ÜNİTE: Grafik Sanatlar (Yazı ve resim birlikteliği (Tipografi girişi))", "7. ÜNİTE: Kukla Yapımı (Hareketli figür tasarımları)", "8. ÜNİTE: Sanat Galerisi (Sınıf sergisi planlama ve sunum)"],`,
    '5': `    'Görsel Sanatlar': ["1. ÜNİTE: Görsel Algı (Optik illüzyonlar ve göz yanılsamaları)", "2. ÜNİTE: Leke ve Ton (Kurşun kalemle derecelendirme çalışmaları)", "3. ÜNİTE: Renk Armonileri (Monokromatik (tek renk) tasarımlar)", "4. ÜNİTE: Seramik Sanatı (Çimdik ve fitil tekniği ile form oluşturma)", "5. ÜNİTE: Doğa ve Peyzaj (Manzara resminde derinlik)", "6. ÜNİTE: Dijital Sanat - I (Tablet ve bilgisayarda çizim araçları)", "7. ÜNİTE: Kültürel Motifler (Çini ve hat sanatına giriş)", "8. ÜNİTE: Afiş Tasarımı (Belirli bir konu üzerine görsel mesaj oluşturma)"],`,
    '6': `    'Görsel Sanatlar': ["1. ÜNİTE: Anatomi ve Oran-Orantı (Hareketli figür çizimleri)", "2. ÜNİTE: Açık-Koyu Etkisi (Desen çalışmalarında hacimleme)", "3. ÜNİTE: Baskı Teknikleri - II (Linol veya şablon (stok) baskı)", "4. ÜNİTE: Perspektif Kuralları (Tek kaçışlı perspektif çizimi)", "5. ÜNİTE: Modern Sanat Akımları (Kübizm ve Empresyonizm (İzlenimcilik))", "6. ÜNİTE: Logo ve Amblem (Kurumsal kimlik tasarım mantığı)", "7. ÜNİTE: Heykel ve Mekan (Kamusal alandaki heykelleri tanıma)", "8. ÜNİTE: Fotoğraf Sanatı (Kompozisyon kuralları ve ışık)"],`,
    '7': `    'Görsel Sanatlar': ["1. ÜNİTE: Renk Teorisi ve Psikolojisi (Renk çemberi ve zıtlıklar)", "2. ÜNİTE: İki Kaçışlı Perspektif (Köşe görünümlü yapı çizimleri)", "3. ÜNİTE: Tekstil Sanatı (Kumaş boyama veya dokuma denemeleri)", "4. ÜNİTE: Minyatür Sanatı (Geleneksel minyatür teknikleri ve hikayeleştirme)", "5. ÜNİTE: Dışavurumculuk (Ekspresyonizm) (Duyguların renklerle anlatımı)", "6. ÜNİTE: Pop-Art (Popüler kültürün sanatla buluşması)", "7. ÜNİTE: Stop-Motion (Görsellerle basit animasyon oluşturma)", "8. ÜNİTE: Estetik ve Etik (Sanatta özgünlük ve intihal)"],`,
    '8': `    'Görsel Sanatlar': ["1. ÜNİTE: Gölgeleme ve Desen (Kömür kalem (füzen) teknikleri)", "2. ÜNİTE: İmgesel Tasarım (Hayalden kompozisyon kurma)", "3. ÜNİTE: Endüstriyel Tasarım (Ürün geliştirme ve estetik)", "4. ÜNİTE: Sanat Tarihi Kronolojisi (Rönesans’tan günümüze yolculuk)", "5. ÜNİTE: Soyut Sanat (Form ve rengin serbest kullanımı)", "6. ÜNİTE: Enstalasyon (Yerleştirme) (Mekana özgü sanat çalışmaları)", "7. ÜNİTE: Portre ve Karakter (Farklı duyguların yüz ifadelerine yansıması)", "8. ÜNİTE: Geleceğin Sanatı (Yapay zeka ve dijital enstalasyonlar)"],`,
    '9': `    'Görsel Sanatlar': ["1. ÜNİTE: Görsel Okuryazarlık (İmajları okuma ve anlamlandırma)", "2. ÜNİTE: Çizgi ve Form (Temel sanat eğitimi ilkeleri)", "3. ÜNİTE: Renk Bilgisi ve Uygulama (Guaj ve sulu boya teknikleri)", "4. ÜNİTE: Perspektif ve Hacim (Nesne etütleri ve mekan çizimi)", "5. ÜNİTE: Antik Sanat (Mezopotamya, Mısır ve Anadolu uygarlıkları)", "6. ÜNİTE: Sanat ve Toplum (Sanatın toplumsal değişimdeki rolü)", "7. ÜNİTE: Dijital İllüstrasyon (Grafik tablet uygulamaları)", "8. ÜNİTE: Sanat Eleştirisi Yöntemleri (Betimleme, analiz, yorum ve yargı)"],`,
    '10': `    'Görsel Sanatlar': ["1. ÜNİTE: Yağlı Boya/Akrilik Teknikleri (Katmanlı boyama yöntemleri)", "2. ÜNİTE: Figüratif Kompozisyon (Grup figür yerleşimleri)", "3. ÜNİTE: Batı Sanatı Tarihi (Barok, Rokoko ve Klasisizm)", "4. ÜNİTE: Grafik Tasarım ve Reklam (Görsel iletişim tasarımı)", "5. ÜNİTE: Geleneksel Türk Sanatları (Tezhip, Kat’ı ve Ebru derinleşme)", "6. ÜNİTE: İç Mekan Tasarımı (Dekorasyon ve estetik planlama)", "7. ÜNİTE: Sanat ve Teknoloji (Video-art ve dijital kolaj)", "8. ÜNİTE: Müze ve Galeri Yönetimi (Küratörlük kavramına giriş)"],`,
    '11': `    'Görsel Sanatlar': ["1. ÜNİTE: İleri Desen Çalışmaları (Canlı modelden çizimler)", "2. ÜNİTE: Modernizmden Postmodernizme (Sanat kuramları)", "3. ÜNİTE: Moda ve Kostüm Tasarımı (Tekstil ve estetik birlikteliği)", "4. ÜNİTE: Sinematografi (Sinemanın görsel dili ve estetiği)", "5. ÜNİTE: Çağdaş Türk Sanatı (Cumhuriyet dönemi sanatçıları)", "6. ÜNİTE: Sanat Felsefesi (Estetik) (Güzellik kavramı ve sanat tanımları)", "7. ÜNİTE: Çevresel Sanat (Land Art) (Doğayı sanat malzemesi olarak kullanma)", "8. ÜNİTE: Portfolyo Hazırlama (Sanatsal çalışmaları biriktirme ve sunma)"],`,
    '12': `    'Görsel Sanatlar': ["1. ÜNİTE: Kişisel Üslup Geliştirme (Kendi sanatsal dilini bulma)", "2. ÜNİTE: Disiplinlerarası Sanat (Müzik, edebiyat ve resim etkileşimi)", "3. ÜNİTE: Güncel Sanat Etkinlikleri (Bienaller ve sanat fuarları)", "4. ÜNİTE: Kreatif Endüstriler (Sanatla ilgili kariyer basamakları)", "5. ÜNİTE: Kamusal Sanat (Şehir mimarisi ve estetik dokunuşlar)", "6. ÜNİTE: Sanat ve Psikoloji (Sanat terapisine giriş)", "7. ÜNİTE: Yapay Zeka Sanatı ve Telif (Algoritmik sanatın hukuki boyutu)", "8. ÜNİTE: Mezuniyet Projesi (Bağımsız bir sanat eseri üretimi ve sergilenmesi)"],`
};

let lines = input.split(/\r?\n/);
let outputLines = [];
let grade = 1;

for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    
    if (line.trim() === '},') {
        if (grade <= 12) {
            outputLines.push(btyBlocks[grade]);
            outputLines.push(artBlocks[grade]);
        }
        outputLines.push(line);
        grade++;
    } else if (line.trim() === '};' && grade === 12) {
        outputLines.push(btyBlocks[grade]);
        outputLines.push(artBlocks[grade]);
        outputLines.push('  },');
        outputLines.push('};');
        grade++;
    } else {
        outputLines.push(line);
    }
}

fs.writeFileSync('src/curriculum.js', outputLines.join('\n'), 'utf8');
console.log('Done mapping, processed', grade - 1, 'grades.');
